/** Everyday words for each audited line. `bookkeeping` marks entries that are not cash actually spent or received. */
export const plain:Record<string,{en:string;hi:string;what:string;whatHi:string;bookkeeping?:boolean}>={
 'property-water-tax':{en:'Home & water taxes',hi:'घर और पानी के कर',what:'Tax on homes, shops and land, plus water charges. Includes amounts billed but not yet paid.',whatHi:'घर, दुकान और ज़मीन पर कर, साथ में पानी का शुल्क। इसमें वह राशि भी है जिसका बिल बना पर अभी भुगतान नहीं हुआ।'},
 'lbt-gst':{en:'Share from Maharashtra (GST)',hi:'महाराष्ट्र से हिस्सा (जीएसटी)',what:'The State pays the city this money because GST replaced the old local tax.',whatHi:'राज्य यह पैसा शहर को देता है क्योंकि जीएसटी ने पुराने स्थानीय कर की जगह ली।'},
 'fees-user-charges':{en:'Building permits & fees',hi:'भवन अनुमति और शुल्क',what:'Fees for building permission, licences and city services.',whatHi:'भवन अनुमति, लाइसेंस और शहर की सेवाओं का शुल्क।'},
 'revenue-grants':{en:'Grants for schemes',hi:'योजनाओं के अनुदान',what:'Money from Central and State schemes, such as housing and health.',whatHi:'केंद्र और राज्य की योजनाओं से पैसा, जैसे आवास और स्वास्थ्य।'},
 'interest-earned':{en:'Interest on savings',hi:'बचत पर ब्याज',what:'Interest the city earns on its bank deposits.',whatHi:'शहर को अपनी बैंक जमा पर मिलने वाला ब्याज।'},
 'rental-income':{en:'Rent from city property',hi:'शहर की संपत्ति का किराया',what:'Rent from shops, halls, land and buildings the city owns.',whatHi:'शहर की दुकानों, हॉल, ज़मीन और इमारतों का किराया।'},
 'other-income':{en:'Other income',hi:'अन्य आय',what:'Smaller items such as fines and lapsed deposits.',whatHi:'छोटी मदें, जैसे जुर्माना और ज़ब्त जमा।'},
 'sales-hire':{en:'Sales & hire charges',hi:'बिक्री और किराया शुल्क',what:'Selling items and hiring out equipment.',whatHi:'सामान बेचना और उपकरण किराये पर देना।'},
 'other-taxes':{en:'Entertainment tax share',hi:'मनोरंजन कर का हिस्सा',what:'The city’s share of entertainment tax.',whatHi:'मनोरंजन कर में शहर का हिस्सा।'},
 'establishment':{en:'Staff salaries & pensions',hi:'कर्मचारियों का वेतन और पेंशन',what:'Pay and pensions for teachers, health workers, engineers, cleaners and other staff.',whatHi:'शिक्षकों, स्वास्थ्यकर्मियों, इंजीनियरों, सफ़ाईकर्मियों और अन्य कर्मचारियों का वेतन और पेंशन।'},
 'provision-overdues':{en:'Set aside for unpaid taxes',hi:'बकाया कर के लिए अलग रखा',what:'Not money spent. An accounting entry for old taxes and rent that may never be collected.',whatHi:'यह ख़र्च नहीं है। पुराने कर और किराये के लिए हिसाब की प्रविष्टि जो शायद कभी वसूल न हों।',bookkeeping:true},
 'operations-maintenance':{en:'Running the city',hi:'शहर चलाना',what:'Electricity, water supply, garbage collection, cleaning and contract staff.',whatHi:'बिजली, पानी की आपूर्ति, कचरा संग्रह, सफ़ाई और ठेका कर्मचारी।'},
 'grants-subsidies':{en:'Grants to other bodies',hi:'अन्य संस्थाओं को अनुदान',what:'Grants and contributions the city gives to other public bodies.',whatHi:'शहर द्वारा अन्य सार्वजनिक संस्थाओं को दिए गए अनुदान और अंशदान।'},
 'administrative':{en:'Offices & administration',hi:'कार्यालय और प्रशासन',what:'Office running costs, legal fees, printing, phones and vehicles.',whatHi:'कार्यालय का ख़र्च, क़ानूनी शुल्क, छपाई, फ़ोन और वाहन।'},
 'repairs-assets':{en:'Repairs: roads, pipes, buildings',hi:'मरम्मत: सड़क, पाइप, इमारतें',what:'Fixing existing roads, water lines, drains, bridges and buildings. New construction is not included here.',whatHi:'मौजूदा सड़कों, पानी की लाइनों, नालियों, पुलों और इमारतों की मरम्मत। नया निर्माण इसमें शामिल नहीं।'},
 'interest-finance':{en:'Interest on loans',hi:'कर्ज़ पर ब्याज',what:'Interest on money the city borrowed through municipal bonds.',whatHi:'नगर बॉन्ड से लिए कर्ज़ पर ब्याज।'},
 'miscellaneous':{en:'Miscellaneous',hi:'विविध',what:'Small items that fit nowhere else.',whatHi:'छोटी मदें जो कहीं और नहीं आतीं।'},
 'nmam-110':{en:'Local taxes (mainly property tax)',hi:'स्थानीय कर (मुख्यतः संपत्ति कर)',what:'Taxes the city collects itself, mainly property tax. In some years this also includes tax shares passed on by the State.',whatHi:'शहर द्वारा स्वयं वसूले कर, मुख्यतः संपत्ति कर।'},
 'nmam-120':{en:'Share of State taxes',hi:'राज्य करों में हिस्सा',what:'Money the State passes on to the city, such as compensation for taxes the State now collects.',whatHi:'राज्य द्वारा शहर को दिया गया पैसा, जैसे राज्य द्वारा वसूले करों की क्षतिपूर्ति।'},
 'nmam-130':{en:'Rent from city property',hi:'शहर की संपत्ति का किराया',what:'Rent from shops, halls, land and buildings the city owns.',whatHi:'शहर की दुकानों, हॉल, ज़मीन और इमारतों का किराया।'},
 'nmam-140':{en:'Fees & service charges',hi:'शुल्क और सेवा प्रभार',what:'Building permissions, licences, water and other service charges.',whatHi:'भवन अनुमति, लाइसेंस, पानी और अन्य सेवा शुल्क।'},
 'nmam-150':{en:'Sales & hire charges',hi:'बिक्री और किराया शुल्क',what:'Selling items and hiring out equipment.',whatHi:'सामान बेचना और उपकरण किराये पर देना।'},
 'nmam-160':{en:'Grants from State & Centre',hi:'राज्य और केंद्र से अनुदान',what:'Grants for running costs and schemes from the State and Central governments.',whatHi:'राज्य और केंद्र सरकार से योजनाओं और ख़र्च के लिए अनुदान।'},
 'nmam-170':{en:'Income from investments',hi:'निवेश से आय',what:'Returns on the city’s investments.',whatHi:'शहर के निवेश से आय।'},
 'nmam-171':{en:'Interest on savings',hi:'बचत पर ब्याज',what:'Interest on the city’s bank deposits.',whatHi:'शहर की बैंक जमा पर ब्याज।'},
 'nmam-180':{en:'Other income',hi:'अन्य आय',what:'Smaller items such as fines.',whatHi:'छोटी मदें, जैसे जुर्माना।'},
 'nmam-100':{en:'Other income',hi:'अन्य आय',what:'Income not classified elsewhere.',whatHi:'अन्य वर्गीकृत न की गई आय।'},
 'nmam-210':{en:'Staff salaries & pensions',hi:'कर्मचारियों का वेतन और पेंशन',what:'Pay, allowances and pensions of city staff.',whatHi:'शहर के कर्मचारियों का वेतन, भत्ते और पेंशन।'},
 'nmam-220':{en:'Offices & administration',hi:'कार्यालय और प्रशासन',what:'Office costs, fees, printing, phones and vehicles.',whatHi:'कार्यालय ख़र्च, शुल्क, छपाई, फ़ोन और वाहन।'},
 'nmam-230':{en:'Running the city',hi:'शहर चलाना',what:'Water supply, cleaning, garbage, street lights, power and repairs.',whatHi:'पानी, सफ़ाई, कचरा, स्ट्रीट लाइट, बिजली और मरम्मत।'},
 'nmam-240':{en:'Interest on loans',hi:'कर्ज़ पर ब्याज',what:'Interest on money the city borrowed.',whatHi:'शहर द्वारा लिए कर्ज़ पर ब्याज।'},
 'nmam-250':{en:'Events & programmes',hi:'कार्यक्रम',what:'Programmes run by the city.',whatHi:'शहर द्वारा चलाए गए कार्यक्रम।'},
 'nmam-260':{en:'Grants to other bodies',hi:'अन्य संस्थाओं को अनुदान',what:'Grants and contributions the city gives to other bodies.',whatHi:'शहर द्वारा अन्य संस्थाओं को अनुदान।'},
 'nmam-270':{en:'Set aside for unpaid dues',hi:'बकाया के लिए अलग रखा',what:'Not money spent. An accounting provision for dues that may never be collected.',whatHi:'यह ख़र्च नहीं है। वसूल न हो सकने वाले बकाये के लिए प्रावधान।',bookkeeping:true},
 'nmam-271':{en:'Miscellaneous',hi:'विविध',what:'Small items that fit nowhere else.',whatHi:'छोटी मदें।'},
 'nmam-272':{en:'Wear and tear (depreciation)',hi:'टूट-फूट (मूल्यह्रास)',what:'Not money spent this year. An accounting estimate of how much roads, buildings and equipment wore out.',whatHi:'इस साल का ख़र्च नहीं। सड़कों, इमारतों और उपकरणों की टूट-फूट का हिसाबी अनुमान।',bookkeeping:true},
 'nmam-200':{en:'Other spending',hi:'अन्य ख़र्च',what:'Spending not classified elsewhere.',whatHi:'अन्य वर्गीकृत न किया गया ख़र्च।'},
 'programme':{en:'Events & programmes',hi:'कार्यक्रम',what:'Awards, training, health and cultural programmes.',whatHi:'पुरस्कार, प्रशिक्षण, स्वास्थ्य और सांस्कृतिक कार्यक्रम।'}
};
