'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {CalendarClock,ArrowDownLeft,ArrowUpRight,ArrowRight,BarChart3,Building2,ChevronDown,ChevronRight,CheckCircle2,CircleHelp,Coins,Compass,Database,ExternalLink,FileText,Globe2,GraduationCap,HeartPulse,House,IndianRupee,Info,Landmark,Languages,Leaf,MapPin,Menu,ReceiptText,Search,ShieldCheck,Sparkles,TrafficCone,Users,Wallet,X,Activity,SlidersHorizontal,HandCoins,LockKeyhole} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
import type {Dataset,MoneyRecord,ShareRecord,Source} from '../../../packages/schema/index';
import {geographies,SIGNAL_DISCLAIMER,NO_DATA} from '../../../packages/schema/index';
import {apportion,formatMoney,shareBasisPoints} from '../../../packages/calculations/index';
import {demonstrationSignals} from '../../../packages/signals/index';
import IndiaMap from './IndiaMap';
import HomeAtlas from './HomeAtlas';
import TaxExperience from './TaxExperience';
import MoneyStory,{plain} from './MoneyStory';
import DataFlow from './DataFlow';
import {staticApi} from '../lib/static-api';
import {localProvider,executeQuery} from '../../api/query';
import type {ConnectorStatus} from '../../api/service';
import {ContractsExplorer,ContractorsExplorer,LiveSignals} from './Contracts';
import {ProjectsList} from './Projects';
import {PlaceSearch,type Place} from './PlaceSearch';
import {LoadError} from './LoadError';
import {PlaceSheet,type SheetMode} from './PlaceSheet';
import {categoryColor} from '../lib/tiles';
import {NATIONAL,VALUE_TYPE} from '../lib/meaning';
import {Concern,type ConcernSubject} from './Concern';
import {useCityIndex,useStateCities,useCity,cityRecords,CityTrend,PUNE_CITYFINANCE_ID,shortCityName,type IndexCity} from './Cities';
import type {City} from '../../../connectors/cityfinance/index';
import type {CityDot} from './IndiaMap';
import {Suspense} from 'react';
type Lang='en'|'hi';
// Feedback channels, set at build time (see docs/operations.md). Unset = link hidden.
const REPO_URL=process.env.NEXT_PUBLIC_REPO_URL??'';
const CONTACT_EMAIL=process.env.NEXT_PUBLIC_CONTACT_EMAIL??'';
const nav:[string,string,string,LucideIcon][]=[['home','Home','होम',House],['explore','Explore','खोजें',Compass],['my-tax','My Tax','मेरा कर',ReceiptText],['projects','Projects','परियोजनाएं',MapPin],['contracts','Contracts','अनुबंध',FileText],['contractors','Contractors','ठेकेदार',Building2],['schemes','Schemes & Benefits','योजनाएं और लाभ',HandCoins],['signals','Signals','संकेत',Activity],['ask','Ask Paisa','पैसा से पूछें',Sparkles]];
const colors=['#24857b','#e9a956','#778bc6','#b585af','#739c65','#d18766','#82a9b4','#949196'];
const icons:Record<string,LucideIcon>={interest:Landmark,defence:ShieldCheck,transport:TrafficCone,education:GraduationCap,health:HeartPulse,agriculture:Leaf,rural:House,food:HandCoins,pension:Users};
const valueLabels={BE:'Budget Estimate',RE:'Revised Estimate',ACTUAL:'Actual',RELEASE:'Fund release',TENDER_VALUE:'Tender value',AWARDED_VALUE:'Awarded contract value',PAYMENT:'Actual payment',SANCTIONED:'Sanctioned amount'};
function Official({hi=false}:{hi?:boolean}){return <span className="badge official"><span/>{hi?'आधिकारिक':'Official'}</span>;}
function Amount({record,onClick,compact=true}:{record:MoneyRecord;onClick:(r:MoneyRecord)=>void;compact?:boolean}){return <button className="amount" onClick={()=>onClick(record)} aria-label={`View provenance for ${record.label}: ${formatMoney(record.amountRupees)}`}><span>{formatMoney(record.amountRupees,compact)}</span><Info size={13}/></button>;}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><span className="empty-icon"><Database size={25}/></span><h3>{title}</h3><p>{text}</p><Link className="text-link" href="/sources">View data coverage <ArrowRight size={15}/></Link></div>;}
export default function Paisa({dataset,page,runSummary=null}:{dataset:Dataset;page:string;runSummary?:string|null}){
 const [lang,setLang]=useState<Lang>('en'),[detailed,setDetailed]=useState(false),[menu,setMenu]=useState(false),[selected,setSelected]=useState<MoneyRecord|null>(null);
 const [exploreTab,setExploreTab]=useState('expenditure');const router=useRouter();const hi=lang==='hi';
 const t=(en:string,hindi:string)=>hi?hindi:en;
 useEffect(()=>{setLang(localStorage.getItem('paisa-lang')==='hi'?'hi':'en');setDetailed(localStorage.getItem('paisa-detail')==='true');},[]);
 useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('paisa-lang',lang);},[lang]);
 useEffect(()=>{localStorage.setItem('paisa-detail',String(detailed));},[detailed]);
 const current=dataset.records.filter(r=>r.fiscalYear==='2026-27'&&r.valueType==='BE');
 const overview=(metric:string)=>current.find(r=>r.group==='overview'&&r.metric===metric)!;
 const actual=(metric:string)=>dataset.records.find(r=>r.sourceId==='cga'&&r.metric===metric)!;
 const spend=current.filter(r=>r.group==='expenditure').sort((a,b)=>Number(BigInt(b.amountRupees)-BigInt(a.amountRupees)));
 const monthlyPeriod=actual('total-expenditure').period.replace(' (provisional, unaudited)','');
 const title=nav.find(n=>n[0]===page)?.[hi?2:1]??(page==='sources'?t('Data Sources','डेटा स्रोत'):t('About PAISA','पैसा के बारे में'));
 const navigate=(p:string)=>{setMenu(false);router.push('/'+(p==='home'?'':p));};
 return <div className="app-shell">
  <a className="skip" href="#main">{t('Skip to content','मुख्य सामग्री पर जाएं')}</a>
  {menu&&<button className="sidebar-scrim" aria-label="Close menu" onClick={()=>setMenu(false)}/>}
  <aside className={`sidebar ${menu?'open':''}`} aria-label={t('Main navigation','मुख्य नेविगेशन')}>
   <Link href="/" className="brand" aria-label="PAISA home"><span className="brand-mark"><IndianRupee size={25} strokeWidth={2.8}/></span><span>paisa<span className="brand-dot">.</span><small>PUBLIC MONEY. PUBLIC KNOWLEDGE.</small></span></Link>
   <div className="nav-caption">{t('YOUR MONEY, EXPLAINED','आपका पैसा, आसान भाषा में')}</div>
   <nav>{nav.map(([id,en,hn,Icon])=><Link key={id} href={'/'+(id==='home'?'':id)} onClick={()=>setMenu(false)} className={`nav-item ${page===id?'active':''}`} aria-current={page===id?'page':undefined}><Icon size={19}/><span>{hi?hn:en}</span>{id==='ask'&&<span className="tiny-new">BETA</span>}</Link>)}</nav>
   <div className="sidebar-bottom"><Link className={`nav-item ${page==='sources'?'active':''}`} href="/sources"><Database size={18}/>{t('Data Sources','डेटा स्रोत')}</Link><Link className={`nav-item ${page==='about'?'active':''}`} href="/about"><CircleHelp size={18}/>{t('About Paisa','पैसा के बारे में')}</Link><div className="independent"><span className="dot"/>{t('Independent. Open source.','स्वतंत्र। ओपन सोर्स।')}<small>{t('Built for every citizen.','हर नागरिक के लिए।')}</small></div></div>
  </aside>
  <div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Open navigation"><Menu size={22}/></button><span>{t('India','भारत')}</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="header-controls"><button className="language-button" onClick={()=>setLang(hi?'en':'hi')}><Languages size={16}/>{hi?'English':'हिन्दी'}</button><div className="mode-switch" aria-label="Display mode"><button aria-pressed={!detailed} className={!detailed?'chosen':''} onClick={()=>setDetailed(false)}>{t('Simple','सरल')}</button><button aria-pressed={detailed} className={detailed?'chosen':''} onClick={()=>setDetailed(true)}>{t('Detailed','विस्तृत')}</button></div><span className="fiscal"><span className="dot"/> FY 2026–27</span></div></header>
  <main id="main" className={`page-${page}`}>
   {page==='home'?<>
    <HomeAtlas dataset={dataset} hi={hi} onSource={setSelected}/>
    <div className="section-line"><h2>{t('India, at a glance','भारत, एक नज़र में')}</h2><span className="muted small"><span className="dot"/>{t('Official budget & monthly accounts','आधिकारिक बजट और मासिक खाते')}</span></div>
    <section className="stats-grid" aria-label="India financial overview">
     <div className="stat-card"><div className="stat-top"><span className="stat-icon mint"><ArrowDownLeft size={21}/></span><Official hi={hi}/></div><h3>{t('Money received so far','अब तक प्राप्त धन')}</h3><Amount record={actual('total-receipts')} onClick={setSelected}/><p>{t('Non-debt receipts','ऋण-भिन्न प्राप्तियां')+' · '+monthlyPeriod}</p><div className="stat-footer"><span>{t('Provisional actual','अनंतिम वास्तविक')}</span><button onClick={()=>{setExploreTab('revenue');navigate('explore');}} aria-label="Explore receipts"><ArrowUpRight size={18}/></button></div></div>
     <div className="stat-card"><div className="stat-top"><span className="stat-icon peach"><ArrowUpRight size={21}/></span><Official hi={hi}/></div><h3>{t('Budgeted expenditure','बजट में निर्धारित व्यय')}</h3><Amount record={overview('total-expenditure')} onClick={setSelected}/><p>{t('Full-year plan · FY 2026–27','पूरे वर्ष की योजना · वित्त वर्ष 2026–27')}</p><div className="stat-footer"><span>{t('Budget Estimate','बजट अनुमान')}</span><button onClick={()=>navigate('explore')} aria-label="Explore expenditure"><ArrowUpRight size={18}/></button></div></div>
     <div className="stat-card"><div className="stat-top"><span className="stat-icon lavender"><BarChart3 size={21}/></span><Official hi={hi}/></div><h3>{t('Expenditure reported so far','अब तक दर्ज व्यय')}</h3><Amount record={actual('total-expenditure')} onClick={setSelected}/><p>{t('Cumulative','संचयी')+' · '+monthlyPeriod}</p><div className="stat-footer"><span>{t('Provisional actual','अनंतिम वास्तविक')}</span><button onClick={()=>setSelected(actual('total-expenditure'))} aria-label="View expenditure source"><ArrowUpRight size={18}/></button></div></div>
    </section>
    <div className="context-note"><Info size={14}/>{t('A budget is a plan. Actuals show what has been reported. They’re always labelled separately.','बजट एक योजना है। वास्तविक आंकड़े दर्ज प्राप्ति और व्यय दिखाते हैं। दोनों को अलग दर्शाया जाता है।')}</div>
    <div className="section-line space-above"><div><h2>{t('Start with a little curiosity','एक छोटे सवाल से शुरू करें')}</h2><p>{t('Big numbers. Everyday questions.','बड़े आंकड़े। रोज़मर्रा के सवाल।')}</p></div></div>
    <section className="quick-grid">{[
     ['explore','Money In','धन की आवक','Where does it come from?','यह कहाँ से आता है?',Wallet,'mint'],['explore','Money Out','धन का व्यय','What is it budgeted for?','यह किसके लिए है?',Coins,'peach'],['my-tax','My Tax','मेरा कर','Put your contribution in context.','अपना योगदान समझें।',ReceiptText,'lavender'],['projects','Projects near you','आपके पास परियोजनाएं','Explore your neighbourhood.','अपना क्षेत्र देखें।',MapPin,'blue']
    ].map(([id,en,hn,desc,descHi,Icon,color],i)=>{const I=Icon as LucideIcon;return <button className="quick-card" key={i} onClick={()=>{if(i===0)setExploreTab('revenue');if(i===1)setExploreTab('expenditure');navigate(String(id));}}><span className={`quick-icon ${color}`}><I size={21}/></span><ArrowUpRight className="quick-arrow" size={17}/><h3>{t(String(en),String(hn))}</h3><p>{t(String(desc),String(descHi))}</p></button>;})}</section>
    <section className="dashboard-columns"><div className="panel spending-panel"><div className="panel-heading"><div><span className="eyebrow small">{t('THE BIG PICTURE','बड़ी तस्वीर')}</span><h2>{t('What’s in the budget?','बजट में क्या है?')}</h2></div><span className="neutral-tag">2026–27 · BE</span></div><p className="muted small">{t('Selected major expenditure categories','प्रमुख व्यय की चुनी गई श्रेणियां')}</p><div className="spending-bars">{spend.slice(0,5).map((r,i)=>{const pct=shareBasisPoints(BigInt(r.amountRupees),BigInt(overview('total-expenditure').amountRupees))/100;return <div className="bar-row" key={r.id}><div className="bar-label"><span><i style={{background:colors[i]}}/>{hi?r.labelHi:r.label}</span><Amount record={r} onClick={setSelected}/></div><div className="bar-track"><div style={{width:`${pct*2.4}%`,background:colors[i]}}/></div><span className="bar-percent">{pct.toFixed(1)}%</span></div>;})}</div><button className="panel-link" onClick={()=>navigate('explore')}>{t('Explore the full expenditure breakdown','व्यय का पूरा विवरण देखें')}<ArrowRight size={16}/></button></div>
     <div className="tax-teaser"><span className="eyebrow small">{t('MAKE IT PERSONAL','अपना योगदान समझें')}</span><span className="receipt-art"><ReceiptText size={48} strokeWidth={1.3}/><i>₹</i></span><h2>{t('Your tax.','आपका कर।')}<br/>{t('A bigger picture.','एक बड़ी तस्वीर।')}</h2><p>{t('See how your contribution compares with the way the Union budget is distributed.','देखें कि आपका योगदान केंद्रीय बजट के अनुपात में कैसे बंटता है।')}</p><div className="tax-example"><span>{t('I paid in taxes','मैंने कर दिया')}</span><strong>₹1,00,000</strong></div><button className="dark-button" onClick={()=>navigate('my-tax')}>{t('Follow my contribution','मेरा योगदान समझें')}<ArrowRight size={17}/></button><small><LockKeyhole size={12}/>{t('No login. No personal details.','लॉगिन या निजी जानकारी की जरूरत नहीं।')}</small></div></section>
    <section className="trust-strip"><ShieldCheck size={28}/><div><h3>{t('Public data. Open methods. No political lens.','सार्वजनिक डेटा। खुली पद्धति। निष्पक्ष दृष्टि।')}</h3><p>{t('Every number has a source. Every gap is visible. Every citizen is welcome.','हर आंकड़े का स्रोत है। हर कमी स्पष्ट है। हर नागरिक का स्वागत है।')}</p></div><Link href="/about">{t('Our promise','हमारा वादा')}<ArrowUpRight size={16}/></Link></section>
    <section className="more-grid">{[['schemes','Schemes & Benefits','योजनाएं और लाभ',HandCoins],['contracts','Contracts','अनुबंध',FileText],['contractors','Contractors','ठेकेदार',Building2],['signals','Signals','संकेत',Activity]].map(([id,en,hn,Icon])=>{const I=Icon as LucideIcon;return <Link href={'/'+id} key={String(id)}><I size={18}/>{t(String(en),String(hn))}<ChevronRight size={15}/></Link>;})}</section>
   </>:<>
    <div className="page-heading"><span className="eyebrow"><span className="mini-line"/> {t('PUBLIC MONEY, MADE UNDERSTANDABLE','सार्वजनिक धन, आसान भाषा में')}</span><h1>{title}<span className="accent-dot">.</span></h1><p>{({explore:t('Follow the numbers. Understand the difference between a plan and expenditure.','आंकड़े देखें। योजना और वास्तविक व्यय का अंतर समझें।'),'my-tax':t('A personal way to understand a shared budget.','साझा बजट को समझने का एक व्यक्तिगत तरीका।'),projects:t('Start with a place. See how far the public data goes.','एक जगह चुनें। देखें कि सार्वजनिक डेटा कहाँ तक उपलब्ध है।'),signals:t('Reproducible observations. Context before conclusions.','दोहराए जा सकने वाले विश्लेषण। निष्कर्ष से पहले संदर्भ।'),sources:t('The evidence behind every number.','हर आंकड़े के पीछे का प्रमाण।'),ask:t('Ask a question. Get an answer grounded in published records.','सवाल पूछें। प्रकाशित आंकड़ों पर आधारित जवाब पाएं।')})[page]??t('Official records, clear definitions and visible data gaps.','आधिकारिक रिकॉर्ड, स्पष्ट परिभाषाएं और डेटा की कमियां।')}</p></div>
    {page==='explore'&&<Explore dataset={dataset} hi={hi} detailed={detailed} tab={exploreTab} setTab={setExploreTab} onSource={setSelected}/>}
    {page==='my-tax'&&<TaxExperience dataset={dataset} hi={hi} onSource={setSelected}/>}
    {page==='projects'&&<Geography hi={hi} dataset={dataset} detailed={detailed} onSource={setSelected}/>}
    {(page==='contracts'||page==='contractors')&&<><div className="info-banner"><Info size={18}/>{t('Awarded value is what a contract was awarded for. It is not money actually paid, and payment records are not public. Connected so far: Assam state contracts.','आवंटित मूल्य वह है जिस पर अनुबंध दिया गया, वास्तविक भुगतान नहीं; भुगतान रिकॉर्ड सार्वजनिक नहीं हैं। अभी जुड़ा: असम राज्य के अनुबंध।')}</div>{dataset.contractsSummary&&<div className="contract-strip"><div><strong>{dataset.contractsSummary.awards.toLocaleString('en-IN')}</strong><span>{t('contract awards','अनुबंध')}</span></div><div><strong>{dataset.contractsSummary.contractors.toLocaleString('en-IN')}</strong><span>{t('contractors','ठेकेदार')}</span></div><div><strong>{dataset.contractsSummary.buyers}</strong><span>{t('departments','विभाग')}</span></div><div><strong>{formatMoney(((BigInt(dataset.contractsSummary.checkedTotalPaise)+50n)/100n).toString())}</strong><span>{t('checked awarded value','जांचा गया आवंटित मूल्य')}</span></div><div><strong>{t('Assam','असम')}</strong><span>{t('tenders','निविदाएं')} {dataset.contractsSummary.years[0]}–{dataset.contractsSummary.years.at(-1)}</span></div></div>}<Suspense fallback={null}>{page==='contracts'?<ContractsExplorer hi={hi}/>:<ContractorsExplorer hi={hi}/>}</Suspense></>}
    {page==='schemes'&&<Schemes dataset={dataset} hi={hi} onSource={setSelected}/>}
    {page==='signals'&&<Signals hi={hi}/>}
    {page==='ask'&&<Ask hi={hi} dataset={dataset} onSource={setSelected}/>}
    {page==='sources'&&<><DataFlow dataset={dataset} hi={hi} runSummary={runSummary}/><Sources dataset={dataset} hi={hi}/></>}
    {page==='about'&&<About hi={hi}/>}
   </>}
   <footer><Link href="/">paisa.</Link><span>{t('An independent public-interest project. Not affiliated with or endorsed by any government.','एक स्वतंत्र जनहित परियोजना। किसी सरकार से संबद्ध या समर्थित नहीं।')}</span><span className="footer-links">{REPO_URL&&<a href={`${REPO_URL}/issues/new?template=data-feedback.yml&labels=data-feedback&title=${encodeURIComponent('Data: '+page)}`} target="_blank" rel="noreferrer">{t('Spotted an error or know an official source? Tell us','कोई गलती या आधिकारिक स्रोत? हमें बताएं')}</a>}{CONTACT_EMAIL&&<a href={`mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent('Paisa: '+page)}`}>{t('Email','ईमेल')}</a>}<Link href="/sources">{t('Sources & methodology','स्रोत और पद्धति')}<ArrowUpRight size={13}/></Link></span></footer>
  </main><nav className="phone-nav" aria-label={t('Quick navigation','त्वरित नेविगेशन')}>
   {([['home','Home','होम',House],['projects','Places','जगहें',MapPin],['my-tax','My Tax','मेरा कर',ReceiptText]] as const).map(([id,en,hn,Icon])=><Link key={id} href={id==='home'?'/':`/${id}`} aria-current={page===id?'page':undefined}><Icon size={20}/><span>{t(en,hn)}</span></Link>)}
   <button onClick={()=>setMenu(!menu)} aria-expanded={menu}><Menu size={20}/><span>{t('More','और')}</span></button>
  </nav></div>
  {selected&&<Provenance record={selected} records={dataset.records} source={dataset.sources.find(s=>s.id===selected.sourceId)!} detailed={detailed} hi={hi} close={()=>setSelected(null)}/>}
 </div>;
}
function Explore({dataset,hi,detailed,tab,setTab,onSource}:{dataset:Dataset;hi:boolean;detailed:boolean;tab:string;setTab:(s:string)=>void;onSource:(r:MoneyRecord)=>void}){
 const [selection,setSelection]=useState('2026-27:BE'),[search,setSearch]=useState('');const [fy,type]=selection.split(':');const t=(a:string,b:string)=>hi?b:a;
 const all=dataset.records.filter(r=>r.fiscalYear===fy&&r.valueType===type);const rows=all.filter(r=>r.group===tab&&(`${r.label} ${r.labelHi}`).toLowerCase().includes(search.toLowerCase()));
 const total=all.find(r=>r.group==='overview'&&r.metric===(tab==='revenue'?'revenue-receipts':'total-expenditure'));
 const [comparison,setComparison]=useState(false);
 return <><div className="tabs"><button className={tab==='expenditure'?'selected':''} onClick={()=>setTab('expenditure')}><ArrowUpRight size={17}/>{t('Money Out','धन का व्यय')}</button><button className={tab==='revenue'?'selected':''} onClick={()=>setTab('revenue')}><ArrowDownLeft size={17}/>{t('Money In','धन की आवक')}</button><button className={tab==='geography'?'selected':''} onClick={()=>setTab('geography')}><Globe2 size={17}/>{t('By place','स्थान के अनुसार')}</button></div>
 {tab==='geography'?<Geography hi={hi} dataset={dataset} detailed={detailed} onSource={onSource}/>:<>
 <div className="filter-row"><label className="search-field"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('Find a category…','श्रेणी खोजें…')}/></label><label className="select-label">{t('Data series','डेटा श्रृंखला')}<select value={selection} onChange={e=>setSelection(e.target.value)}><option value="2026-27:BE">2026–27 · Budget Estimate</option><option value="2026-27:ACTUAL">2026–27 · Apr–Aug actual</option><option value="2025-26:BE">2025–26 · Budget Estimate</option><option value="2025-26:RE">2025–26 · Revised Estimate</option><option value="2024-25:ACTUAL">2024–25 · Full-year actual</option></select></label><button className={`outline ${comparison?'pressed':''}`} onClick={()=>setComparison(!comparison)}><BarChart3 size={16}/>{t('Compare','तुलना')}</button></div>
 {total&&<div className="total-banner"><div><span className="eyebrow">{hi?total.labelHi:total.label}</span><Amount record={total} onClick={onSource}/></div><div><Official hi={hi}/><p>{total.period} · {valueLabels[total.valueType]}</p></div></div>}
 {tab==='revenue'&&<div className="info-banner"><Info size={18}/>{t('Tax categories below are gross Union receipts. Revenue receipts above use tax net to the Centre. State devolution and other adjustments explain the difference. GST here is not all-India gross GST collection.','नीचे कर श्रेणियां सकल केंद्रीय प्राप्तियां हैं। ऊपर राजस्व प्राप्तियों में केंद्र का निवल कर शामिल है। राज्यों का हिस्सा और अन्य समायोजन अलग हैं।')}</div>}
 {comparison&&<div className="panel comparison"><h3>{t('Budget versus reported actual','बजट बनाम दर्ज वास्तविक')}</h3><p>{t('Same fiscal year, different periods: full-year plan versus cumulative April–August actual. The remainder is not evidence of under-utilisation.','एक ही वित्त वर्ष, अलग अवधियां: पूरे वर्ष की योजना बनाम अप्रैल–अगस्त के वास्तविक आंकड़े। शेष राशि कम उपयोग का प्रमाण नहीं है।')}</p>{['revenue-receipts','total-expenditure'].map(m=>{const b=dataset.records.find(r=>r.metric===m&&r.fiscalYear==='2026-27'&&r.valueType==='BE')!;const a=dataset.records.find(r=>r.metric===m&&r.sourceId==='cga')!;return <div className="comparison-row" key={m}><strong>{hi?b.labelHi:b.label}</strong><span>BE <Amount record={b} onClick={onSource}/></span><span>{t('Actual','वास्तविक')} <Amount record={a} onClick={onSource}/></span><div className="comparison-track"><span style={{width:`${shareBasisPoints(BigInt(a.amountRupees),BigInt(b.amountRupees))/100}%`}}/></div></div>;})}</div>}
 <div className="panel data-panel"><div className="panel-heading"><h2>{t(tab==='revenue'?'Sources of revenue':'Expenditure by purpose',tab==='revenue'?'राजस्व के स्रोत':'उद्देश्य के अनुसार व्यय')}</h2><span className="neutral-tag">{rows.length} {t('categories','श्रेणियां')}</span></div>{rows.length?<div className="category-list">{rows.map((r,i)=>{const Icon=icons[r.metric]??Coins;return <div className="category-row tappable" key={r.id} onClick={()=>onSource(r)}><span className="category-icon" style={{background:colors[i%colors.length]+'18',color:colors[i%colors.length]}}><Icon size={20}/></span><div className="category-name"><strong>{hi?r.labelHi:r.label}</strong><small>{valueLabels[r.valueType]}{detailed?` · ${r.id}`:''}</small></div><Amount record={r} onClick={onSource}/><button className="icon-button" onClick={e=>{e.stopPropagation();onSource(r);}} aria-label={hi?`${r.labelHi}: अर्थ और स्रोत`:`${r.label}: what it means and its source`}><ChevronRight size={17}/></button></div>;})}</div>:<Empty title={t('This breakdown is not connected','यह विवरण अभी उपलब्ध नहीं है')} text={t('The connected monthly source supplies national aggregates. Category-level monthly actuals are not yet connected.','जुड़े मासिक स्रोत में राष्ट्रीय योग हैं। श्रेणी के अनुसार मासिक आंकड़े अभी नहीं जुड़े हैं।')}/>}</div>
 {tab==='revenue'&&<div className="panel financing"><Landmark size={24}/><div><h3>{t('Borrowing is financing','उधार वित्तपोषण है')}</h3><p>{t('It helps meet the gap between receipts and expenditure. It is shown separately from tax revenue.','यह प्राप्ति और व्यय का अंतर पूरा करता है। इसे कर राजस्व से अलग दिखाया जाता है।')}</p></div>{all.find(r=>r.metric==='borrowing')?<Amount record={all.find(r=>r.metric==='borrowing')!} onClick={onSource}/>:<span>{t('Not connected for this series','इस श्रृंखला के लिए उपलब्ध नहीं')}</span>}</div>}
 </> }</>;
}
function Geography({hi,dataset,detailed,onSource}:{hi:boolean;dataset:Dataset;detailed:boolean;onSource:(r:MoneyRecord)=>void}){
 const [location,setLocation]=useState('india'),[cityId,setCityId]=useState<string|null>(null),[chosenYear,setChosenYear]=useState('2026-27');const t=(a:string,b:string)=>hi?b:a;
 const legacyPune=['pune','pune-urban','pune-rural','pmc'].includes(location);
 const geo=geographies.find(g=>g.id===(legacyPune?'maharashtra':location))!;const ancestors=[];let parent=geo;while(parent){ancestors.unshift(parent);if(!parent.parentId)break;parent=geographies.find(g=>g.id===parent.parentId)!;}
 const states=geographies.filter(g=>g.parentId==='india').sort((a,b)=>a.name.localeCompare(b.name));const stateGeo=ancestors.find(g=>g.type==='state'||g.type==='ut')??null;
 const stateOf=(id:string)=>{let g=geographies.find(x=>x.id===id);while(g&&g.type!=='state'&&g.type!=='ut')g=geographies.find(x=>x.id===g!.parentId);return g?.id;};
 const connected=new Set([...dataset.records.flatMap(r=>r.geographyId?[stateOf(r.geographyId)??'']:[]),...(dataset.shares??[]).map(r=>r.geographyId),...Object.keys(dataset.citiesSummary?.byState??{})].filter(Boolean));
 const labels=Object.fromEntries(states.map(g=>[g.id,hi?g.nameHi:g.name]));
 // Cities: an index for dots, and the open state's full accounts.
 const index=useCityIndex();const {file:stateCities,failed:stateFailed,retry:retryState}=useStateCities(stateGeo?.id??null);
 const openCity=useCallback((id:string)=>{const c=index?.cities.find(x=>x.id===id);if(c?.s)setLocation(c.s);else if(id===PUNE_CITYFINANCE_ID)setLocation('maharashtra');setCityId(id);},[index]);
 useEffect(()=>{if(legacyPune){setLocation('maharashtra');setCityId(PUNE_CITYFINANCE_ID);}},[legacyPune]);
 const lightCity=cityId?stateCities?.cities.find(c=>c.id===cityId)??null:null;const {city,failed:cityFailed,retry:retryCity}=useCity(stateGeo?.id??null,lightCity);
 // Phone bottom sheet: opens at the summary + chart height whenever the place changes.
 const [sheet,setSheet]=useState<SheetMode>('half');useEffect(()=>setSheet('half'),[stateGeo?.id,cityId]);
 const pick=useCallback((p:Place)=>{if(p.kind==='state'){setCityId(null);setLocation(p.id);}else{setLocation(p.stateId);setCityId(p.id);}},[]);
 // Shareable view: ?state=maharashtra&city=<cityfinance id>&year=2022-23 opens exactly this place and year.
 const [fromUrl,setFromUrl]=useState(false);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);const s=q.get('state'),c=q.get('city'),y=q.get('year');
  if(s&&geographies.some(g=>g.id===s&&g.parentId==='india')){setLocation(s);if(c&&/^[a-f0-9]{24}$/.test(c))setCityId(c);}
  if(y&&/^\d{4}-\d{2}$/.test(y))setChosenYear(y);setFromUrl(true);},[]);
 const size=(p:number|null)=>p?Math.min(1,Math.max(0,(Math.log10(p)-4)/3)):0;
 const short=shortCityName;
 // India view: big cities from a small national file. State view: every city in that state's file.
 const dots:CityDot[]=stateGeo?(stateCities?.cities??[]).filter(c=>c.lat!==null&&c.lng!==null).map(c=>({id:c.id,label:short(c.name),lat:c.lat!,lng:c.lng!,size:size(c.population),hasData:c.ys>0})):(index?.cities??[]).map((c:IndexCity)=>({id:c.id,label:short(c.n),lat:c.lat,lng:c.lng,size:size(c.p),hasData:true}));
 const level=cityId?'city':stateGeo?'state':'india';
 const pmcRecords=(fy:string)=>dataset.records.filter(r=>r.geographyId==='pmc'&&r.fiscalYear===fy);
 const cityfinanceSource=dataset.sources.find(x=>x.id===dataset.citiesSummary?.sourceId);
 // City years: cityfinance years, plus PMC's own audited year for Pune.
 const cityYears=city?[...new Set([...Object.keys(city.years),...(city.id===PUNE_CITYFINANCE_ID?[...new Set(dataset.records.filter(r=>r.geographyId==='pmc').map(r=>r.fiscalYear))]:[])])].sort():[];
 const years=level==='india'?[...new Set(dataset.records.filter(r=>r.group==='overview'&&r.sourceId!=='cga').map(r=>r.fiscalYear))].sort():level==='city'?cityYears:[...new Set((dataset.shares??[]).filter(r=>r.geographyId===stateGeo?.id).map(r=>r.fiscalYear))].sort();
 const year=years.includes(chosenYear)?chosenYear:years[years.length-1]??chosenYear;
 const cityRecs=city?(city.id===PUNE_CITYFINANCE_ID&&pmcRecords(year).length?pmcRecords(year):cityfinanceSource?cityRecords(city,year,cityfinanceSource):[]):[];
 const back=useCallback(()=>{if(cityId){setCityId(null);return;}setLocation('india');},[cityId]);
 const cityName=city?shortCityName(city.name):'';
 // For the city story: the previous year with accounts (same source), and every year, for "how it changed".
 const cfYears=city?Object.keys(city.years).sort():[];const prevCfYear=cfYears[cfYears.indexOf(year)-1];
 const storyPrevious=useMemo(()=>{if(!city||!cityfinanceSource||!prevCfYear)return undefined;const r=cityRecords(city,prevCfYear,cityfinanceSource);
  return {year:prevCfYear,income:r.filter(x=>x.group==='municipal-income'),expense:r.filter(x=>x.group==='municipal-expenditure'),sameSource:true};},[city,cityfinanceSource,prevCfYear]);
 const storyHistory=useMemo(()=>city&&cityfinanceSource?cfYears.map(y=>({year:y,records:cityRecords(city,y,cityfinanceSource)})):undefined,[city,cityfinanceSource,cfYears.join()]);
 const stateCityCount=stateGeo?dataset.citiesSummary?.byState[stateGeo.id]??0:0;
 // On narrow screens the year row scrolls sideways; keep the chosen year in view.
 const yearsRow=useRef<HTMLDivElement>(null);
 useEffect(()=>{const row=yearsRow.current;const on=row?.querySelector<HTMLElement>('[aria-pressed="true"]');if(row&&on&&row.scrollWidth>row.clientWidth)row.scrollLeft=on.offsetLeft-(row.clientWidth-on.offsetWidth)/2;},[year,years.length]);
 useEffect(()=>{if(!fromUrl)return;const u=new URL(window.location.href);const set=(k:string,v:string|null)=>{if(v)u.searchParams.set(k,v);else u.searchParams.delete(k);};
  set('state',stateGeo?.id??null);set('city',cityId);set('year',level==='india'?null:year);if(u.href!==window.location.href)window.history.replaceState(window.history.state,'',u);},[fromUrl,stateGeo?.id,cityId,year,level]);
 return <>
 <div className="place-tools"><PlaceSearch hi={hi} onPick={pick}/>
 <label className="select-label place-select">{t('Or choose a state / UT','या राज्य / केंद्र शासित प्रदेश चुनें')}<select value={stateGeo?.id??''} onChange={e=>{setCityId(null);setLocation(e.target.value||'india');}}><option value="">{t('All India','पूरा भारत')}</option>{states.map(g=><option key={g.id} value={g.id}>{hi?g.nameHi:g.name}{connected.has(g.id)?' ●':''}</option>)}</select></label></div>
 <div className="explorer">
  <IndiaMap sheet={sheet} state={stateGeo?.id??null} city={cityId} connected={connected} labels={labels} dots={dots} onState={id=>{setCityId(null);setLocation(id);}} onCity={openCity} onBack={back} hi={hi}/>
  <nav className="map-crumbs" aria-label={t('Where you are','आप कहाँ हैं')}>{ancestors.map((g,i)=><button key={g.id} aria-current={!cityId&&i===ancestors.length-1?'location':undefined} onClick={()=>{setCityId(null);setLocation(g.id);}}>{hi?g.nameHi:g.name}</button>)}{cityId&&<button aria-current="location">{cityName||t('City','शहर')}</button>}</nav>
  {years.length>0&&<div className="map-years" ref={yearsRow} role="group" aria-label={t('Year','वर्ष')}>{years.map(y=><button key={y} aria-pressed={y===year} onClick={()=>setChosenYear(y)}>{y}</button>)}</div>}
  <PlaceSheet mode={sheet} setMode={setSheet} hi={hi}><PlaceCard detailed={detailed} stateId={stateGeo?.id??null} level={level} year={year} dataset={dataset} hi={hi} stateName={stateGeo?(hi?stateGeo.nameHi:stateGeo.name):''} shares={(dataset.shares??[]).filter(x=>x.geographyId===stateGeo?.id)} hasCity={stateGeo?.id==='maharashtra'} openCity={()=>openCity(PUNE_CITYFINANCE_ID)} onSource={onSource} city={city} cityRecs={cityRecs} cityYears={cityYears} onYear={setChosenYear} cityCount={stateCityCount}/></PlaceSheet>
 </div>
 {stateFailed&&<LoadError hi={hi} what={[`Cities in ${labels[stateGeo?.id??'']??''}`,`${labels[stateGeo?.id??'']??''} के शहर`]} onRetry={retryState}/>}
 {cityFailed&&<LoadError hi={hi} what={['This city’s accounts','इस शहर के खाते']} onRetry={retryCity}/>}

 {level==='state'&&stateGeo&&<StateFinance state={stateGeo} shares={(dataset.shares??[]).filter(x=>x.geographyId===stateGeo.id)} sources={dataset.sources} year={year} hi={hi} detailed={detailed} hasCity={false} openCity={()=>openCity(PUNE_CITYFINANCE_ID)}/>}
 {level==='city'&&city&&cityRecs.length>0&&!cityRecs[0].sourceId.startsWith('pmc-')&&<section className="panel muni-panel" id="city-story"><div className="panel-heading"><div><span className="eyebrow small">{city.name} · {year}</span><h2>{t('How the city’s money came in and went out','शहर का पैसा कैसे आया और कहाँ गया')}</h2></div><span className="badge official">{t('Official','आधिकारिक')}</span></div>
  <MoneyStory key={city.id} income={cityRecs.filter(r=>r.group==='municipal-income')} expense={cityRecs.filter(r=>r.group==='municipal-expenditure')} previous={storyPrevious} history={storyHistory} fiscalYear={year} hi={hi} onSource={onSource} place={cityName} placeHi={cityName}/>
  <p className="contract-source"><Info size={14}/>{t('Source','स्रोत')}: {cityRecs[0].sourceId.startsWith('pmc-')?t('Pune Municipal Corporation audited accounts','पुणे महानगरपालिका के लेखापरीक्षित खाते'):<a href={`https://www.cityfinance.in/municipal-data/city/${city.slug}`} target="_blank" rel="noreferrer">cityfinance.in · {city.name}<ExternalLink size={11}/></a>} · {t('Annual accounts on an accrual basis; depreciation and provisions are bookkeeping entries, not cash spent.','उपार्जन आधार पर वार्षिक खाते; मूल्यह्रास और प्रावधान हिसाब की प्रविष्टियाँ हैं, नकद ख़र्च नहीं।')}</p></section>}
 {level==='city'&&city?.id===PUNE_CITYFINANCE_ID&&pmcRecords(year).length>0&&<div id="city-story"><Municipal dataset={dataset} hi={hi} detailed={detailed} onSource={onSource}/></div>}
 {dataset.projectsSummary&&<ProjectsList state={stateGeo?.id??null} stateName={stateGeo?(hi?stateGeo.nameHi:stateGeo.name):''} hi={hi}/>}
 </>;
}
/** "Out of every ₹100" mini bars: exact largest-remainder split, top items plus the rest. */
function Per100({rows,hi,label,onSource,all=false}:{rows:MoneyRecord[];hi:boolean;label:(r:MoneyRecord)=>string;onSource:(r:MoneyRecord)=>void;all?:boolean}){
 const sorted=[...rows].sort((a,b)=>Number(BigInt(b.amountRupees)-BigInt(a.amountRupees)));const parts=apportion(100n,sorted.map(r=>BigInt(r.amountRupees)));
 const n=all?sorted.length:4;const top=sorted.slice(0,n),rest=parts.slice(n).reduce((a,b)=>a+b,0n);
 return <ul className="per100">{top.map((r,i)=><li key={r.id}><button onClick={()=>onSource(r)}><span>{label(r)}</span><strong>₹{parts[i].toString()}</strong></button><i style={{width:`${Number(parts[i])}%`,background:categoryColor(r.metric,colors[i%colors.length])}}/></li>)}{rest>0n&&<li><span className="rest-label"><span>{hi?'बाकी सब':'Everything else'}</span><strong>₹{rest.toString()}</strong></span><i className="rest" style={{width:`${Number(rest)}%`}}/></li>}</ul>;
}
const shareLabels:Record<string,{en:string;hi:string;what:string;whatHi:string}>={
 'own-tax':{en:'State’s own taxes',hi:'राज्य के अपने कर',what:'Taxes the state collects itself, such as its share of GST, stamp duty, vehicle tax and excise.',whatHi:'राज्य द्वारा स्वयं वसूले कर, जैसे जीएसटी का राज्य हिस्सा, स्टांप शुल्क, वाहन कर और उत्पाद शुल्क।'},
 'own-non-tax':{en:'Fees, royalties & other income',hi:'शुल्क, रॉयल्टी और अन्य आय',what:'Mining royalties, fees, interest and dividends earned by the state.',whatHi:'खनन रॉयल्टी, शुल्क, ब्याज और लाभांश।'},
 'union-transfers':{en:'Money from the Union',hi:'केंद्र से पैसा',what:'The state’s share of central taxes plus grants from the Government of India.',whatHi:'केंद्रीय करों में राज्य का हिस्सा और भारत सरकार के अनुदान।'},
 'development':{en:'Development',hi:'विकास',what:'Education, health, agriculture, rural and urban development, welfare and similar services.',whatHi:'शिक्षा, स्वास्थ्य, कृषि, ग्रामीण और शहरी विकास, कल्याण जैसी सेवाएं।'},
 'interest':{en:'Interest on loans',hi:'कर्ज़ पर ब्याज',what:'Interest the state pays on money it borrowed earlier.',whatHi:'पहले लिए कर्ज़ पर राज्य द्वारा दिया गया ब्याज।'},
 'pension':{en:'Pensions',hi:'पेंशन',what:'Pensions paid to retired state government employees.',whatHi:'सेवानिवृत्त राज्य कर्मचारियों को पेंशन।'},
 'administration':{en:'Administration & other non-development',hi:'प्रशासन और अन्य गैर-विकास',what:'Non-development spending other than interest and pensions, such as administration, police and tax collection.',whatHi:'ब्याज और पेंशन के अलावा गैर-विकास ख़र्च, जैसे प्रशासन, पुलिस और कर वसूली।'},
 'other':{en:'Other spending',hi:'अन्य ख़र्च',what:'Revenue spending that RBI does not classify as development or non-development.',whatHi:'राजस्व ख़र्च जिसे RBI विकास या गैर-विकास में नहीं गिनता।'}
};
const periodKind=(k:string,hi:boolean)=>k==='ACTUAL'?(hi?'वास्तविक (लेखा)':'actual accounts'):k==='RE'?(hi?'संशोधित अनुमान':'revised estimate'):(hi?'बजट योजना':'budget plan');
type ShareItem={key:string;weight:bigint;records:ShareRecord[]};
/** Per-₹100 view from RBI ratios (all % of GSDP, so shares are ratios of ratios). Prefers RE over BE for the same year. */
function shareView(shares:ShareRecord[],year:string){
 const kind=(['ACTUAL','RE','BE'] as const).find(k=>shares.some(r=>r.fiscalYear===year&&r.valueType===k));if(!kind)return null;
 const rows=shares.filter(r=>r.fiscalYear===year&&r.valueType===kind);const g=(m:string)=>rows.find(r=>r.metric===m);const n=(m:string)=>BigInt(g(m)?.tenthsOfPercentGsdp??0);
 const pos=(x:bigint)=>x>0n?x:0n;const rr=g('revenue-receipts');if(!rr)return null;
 return {kind,size:(rr.tenthsOfPercentGsdp/10).toFixed(1),rows,
  income:[['own-tax'],['own-non-tax'],['union-transfers']].map(([m])=>({key:m,weight:n(m),records:[g(m)!]})) as ShareItem[],
  spend:[{key:'development',weight:n('development'),records:[g('development')!]},{key:'administration',weight:pos(n('non-development')-n('interest')-n('pension')),records:[g('non-development')!,g('interest')!,g('pension')!]},{key:'interest',weight:n('interest'),records:[g('interest')!]},{key:'pension',weight:n('pension'),records:[g('pension')!]},{key:'other',weight:pos(n('revenue-expenditure')-n('development')-n('non-development')),records:[g('revenue-expenditure')!,g('development')!,g('non-development')!]}].filter(x=>x.weight>0n) as ShareItem[]};
}
function ShareBars({items,hi,all=false,explain=false}:{items:ShareItem[];hi:boolean;all?:boolean;explain?:boolean}){
 const sorted=[...items].sort((a,b)=>Number(b.weight-a.weight));const parts=apportion(100n,sorted.map(i=>i.weight));
 return <ul className="per100">{sorted.map((it,i)=>{const l=shareLabels[it.key];return <li key={it.key}><span className="rest-label"><span>{hi?l.hi:l.en}</span><strong>₹{parts[i].toString()}</strong></span><i style={{width:`${Number(parts[i])}%`,background:colors[i%colors.length]}}/>{(explain||all)&&<small className="share-what">{hi?l.whatHi:l.what}{all&&<> · {it.records.map(r=>`${r.cell}=${(r.tenthsOfPercentGsdp/10).toFixed(1)}%`).join(', ')} {hi?'GSDP का':'of GSDP'}</>}</small>}</li>;})}</ul>;
}
function PlaceCard({level,year,dataset,hi,detailed,stateName,stateId,shares,hasCity,openCity,onSource,city,cityRecs,cityYears,onYear,cityCount}:{level:string;year:string;dataset:Dataset;hi:boolean;detailed:boolean;stateName:string;stateId:string|null;shares:ShareRecord[];hasCity:boolean;openCity:()=>void;onSource:(r:MoneyRecord)=>void;city:City|null;cityRecs:MoneyRecord[];cityYears:string[];onYear:(y:string)=>void;cityCount:number}){
 const t=(a:string,b:string)=>hi?b:a;
 if(level==='city'){
  const inc=cityRecs.filter(r=>r.group==='municipal-income'),out=cityRecs.filter(r=>r.group==='municipal-expenditure');const audited=cityRecs[0]?.sourceId.startsWith('pmc-');
  const plainLabel=(r:MoneyRecord)=>(hi?plain[r.metric]?.hi:plain[r.metric]?.en)??(hi?r.labelHi:r.label);const sum=(x:MoneyRecord[])=>x.reduce((a,r)=>a+BigInt(r.amountRupees),0n).toString();
  if(!city)return <p className="muted small">{t('Loading city…','शहर लोड हो रहा है…')}</p>;
  return <><span className="card-kicker">{t('CITY','शहर')} · {cityRecs.length?year:t('no accounts','खाते नहीं')} · {audited?t('audited','लेखापरीक्षित'):t('annual accounts','वार्षिक खाते')}</span><h2>{shortCityName(city.name)}</h2><p className="card-sub">{city.name}{city.population?` · ${t('population','जनसंख्या')} ${city.population.toLocaleString('en-IN')}`:''}</p>
   {!cityRecs.length?<p className="card-sub">{t('No standardised accounts are published for this city on cityfinance.in yet, so no numbers are shown.','इस शहर के मानकीकृत खाते अभी cityfinance.in पर प्रकाशित नहीं हैं, इसलिए कोई आंकड़ा नहीं।')}</p>:<>
   <div className="card-totals"><div><small>{t('Came in','आया')}</small><strong>{formatMoney(sum(inc))}</strong></div><div><small>{t('Went out','गया')}</small><strong>{formatMoney(sum(out))}</strong></div></div>
   {cityYears.length>1&&<CityTrend city={city} years={cityYears} active={year} hi={hi} onYear={onYear}/>}
   <h3>{t('Every ₹100 came from…','हर ₹100 आया…')}</h3><Per100 all={detailed} rows={inc} hi={hi} label={plainLabel} onSource={onSource}/>
   <h3>{t('Every ₹100 went to…','हर ₹100 गया…')}</h3><Per100 all={detailed} rows={out} hi={hi} label={plainLabel} onSource={onSource}/>
   <button className="primary card-cta" onClick={()=>document.getElementById('city-story')?.scrollIntoView({behavior:'smooth'})}>{t('Watch the city’s money story','शहर के पैसे की कहानी देखें')}<ArrowRight size={16}/></button></>}</>;
 }
 if(level==='state'){const v=shareView(shares,year);const cs=dataset.contractsSummary;const contractChip=cs&&shares[0]?.geographyId===cs.geographyId&&<Link className="city-chip" href="/contracts"><FileText size={16}/><span>{t(`${cs.awards.toLocaleString('en-IN')} public contract awards`,`${cs.awards.toLocaleString('en-IN')} सार्वजनिक अनुबंध`)}<small>{t(`Tenders ${cs.years[0]}–${cs.years.at(-1)} · who won, for how much`,`निविदाएं ${cs.years[0]}–${cs.years.at(-1)} · किसे, कितने में`)}</small></span><ChevronRight size={16}/></Link>;const ps=stateId?dataset.projectsSummary?.byState[stateId]:undefined;const projectChip=ps&&<button className="city-chip project-chip" onClick={()=>document.getElementById('projects')?.scrollIntoView({behavior:'smooth'})}><CalendarClock size={16}/><span>{t(`${ps.projects} big central projects`,`${ps.projects} बड़ी केंद्रीय परियोजनाएं`)}<small>{t(`${ps.delayed} running late · ${ps.overCost} cost more than approved`,`${ps.delayed} देर से · ${ps.overCost} की लागत बढ़ी`)}</small></span><ChevronRight size={16}/></button>;const cityChip=cityCount>0?<p className="city-chip"><MapPin size={16}/><span>{t(`${cityCount} cities with accounts`,`${cityCount} शहरों के खाते उपलब्ध`)}<small>{t('Tap an orange dot on the map','नक्शे पर नारंगी बिंदु पर टैप करें')}</small></span></p>:hasCity&&<button className="city-chip" onClick={openCity}><MapPin size={16}/><span>{t('Pune has city money data','पुणे का शहरी पैसा डेटा है')}<small>{t('Tap to zoom in','ज़ूम करने के लिए टैप करें')}</small></span><ChevronRight size={16}/></button>;
  if(!v)return <><span className="card-kicker">{t('STATE / UT','राज्य / केंद्र शासित प्रदेश')}</span><h2>{stateName}</h2><p className="card-sub">{t('No state budget data is connected here. RBI’s state study covers the 28 states plus Delhi, Jammu & Kashmir and Puducherry. Other Union Territories are funded mainly through the Union budget.','यहाँ राज्य बजट डेटा नहीं जुड़ा है। RBI का अध्ययन 28 राज्यों और दिल्ली, जम्मू-कश्मीर व पुडुचेरी को कवर करता है। अन्य केंद्र शासित प्रदेश मुख्यतः केंद्रीय बजट से चलते हैं।')}</p>{cityChip}</>;
  return <><span className="card-kicker">{t('STATE','राज्य')} · {year} · {periodKind(v.kind,hi)}</span><h2>{stateName}</h2>
   <p className="card-lead">{t(`For every ₹100 the state’s economy produces, the state government’s day-to-day income is about ₹${v.size}.`,`राज्य की अर्थव्यवस्था के हर ₹100 पर राज्य सरकार की रोज़मर्रा की आय लगभग ₹${v.size} है।`)}</p>
   <h3>{t('Every ₹100 of income came from…','आय के हर ₹100…')}</h3><ShareBars items={v.income} hi={hi} all={detailed}/>
   <h3>{t('Every ₹100 of day-to-day spending went to…','रोज़मर्रा के ख़र्च के हर ₹100…')}</h3><ShareBars items={v.spend} hi={hi} all={detailed}/>
   {cityChip}{projectChip}{contractChip}<button className="primary card-cta" onClick={()=>document.getElementById('state-story')?.scrollIntoView({behavior:'smooth'})}>{t('See what each part means','हर हिस्से का अर्थ देखें')}<ArrowRight size={16}/></button></>;}
 const rows=dataset.records.filter(r=>r.sourceId!=='cga'&&r.fiscalYear===year);const kind=['ACTUAL','RE','BE'].find(v=>rows.some(r=>r.valueType===v&&r.group==='overview'))!;
 const pick=(m:string)=>rows.find(r=>r.group==='overview'&&r.metric===m&&r.valueType===kind);const spend=pick('total-expenditure'),borrow=pick('borrowing');
 const kindLabel=kind==='ACTUAL'?t('what was actually spent','जो वास्तव में ख़र्च हुआ'):kind==='RE'?t('revised plan','संशोधित योजना'):t('budget plan','बजट योजना');
 return <><span className="card-kicker">{t('COUNTRY','देश')} · {year} · {kindLabel}</span><h2>{t('India','भारत')}</h2>
  {spend&&<p className="card-lead">{kind==='ACTUAL'?t('The Government of India spent','भारत सरकार ने ख़र्च किए'):t('The Government of India plans to spend','भारत सरकार की ख़र्च योजना')} <button className="inline-amount" onClick={()=>onSource(spend)}>{formatMoney(spend.amountRupees)}</button>{borrow&&<>{t(', of which','; इसमें से')} <button className="inline-amount" onClick={()=>onSource(borrow)}>{formatMoney(borrow.amountRupees)}</button> {t('is borrowed.','उधार है।')}</>}</p>}
  <h3>{t('Every ₹100 spent goes to…','हर ₹100 का ख़र्च…')}</h3><Per100 all={detailed} rows={rows.filter(r=>r.group==='expenditure'&&r.valueType===kind)} hi={hi} label={r=>hi?r.labelHi:r.label} onSource={onSource}/>
  {dataset.projectsSummary&&<button className="city-chip project-chip" onClick={()=>document.getElementById('projects')?.scrollIntoView({behavior:'smooth'})}><CalendarClock size={16}/><span>{t(`${dataset.projectsSummary.projects.toLocaleString('en-IN')} big central projects`,`${dataset.projectsSummary.projects.toLocaleString('en-IN')} बड़ी केंद्रीय परियोजनाएं`)}<small>{t(`${dataset.projectsSummary.delayed.toLocaleString('en-IN')} running late · ${dataset.projectsSummary.overCost} cost more than approved`,`${dataset.projectsSummary.delayed.toLocaleString('en-IN')} देर से · ${dataset.projectsSummary.overCost} की लागत बढ़ी`)}</small></span><ChevronRight size={16}/></button>}
  <p className="card-hint"><MapPin size={14}/>{t('Tap a state, or the Pune dot, to zoom in.','ज़ूम करने के लिए किसी राज्य या पुणे बिंदु पर टैप करें।')}</p></>;
}

function StateFinance({state,shares,sources,year,hi,detailed,hasCity,openCity}:{state:{name:string;nameHi:string};shares:ShareRecord[];sources:Source[];year:string;hi:boolean;detailed:boolean;hasCity:boolean;openCity:()=>void}){
 const t=(a:string,b:string)=>hi?b:a;const name=hi?state.nameHi:state.name;const v=shareView(shares,year);
 const city=hasCity&&<button className="geo-child" onClick={openCity}><Landmark size={18}/><span>{t('Pune Municipal Corporation','पुणे महानगरपालिका')}<small>{t('city accounts connected · see how money came and went','शहर के खाते जुड़े हैं · पैसा कैसे आया और गया देखें')}</small></span><ChevronRight size={17}/></button>;
 if(!v)return <section className="panel state-finance"><div className="panel-heading"><div><span className="eyebrow small">{t('STATE FINANCES','राज्य वित्त')}</span><h2>{t(`Where ${name}’s money comes from and goes`,`${name} का पैसा कहाँ से आता है और कहाँ जाता है`)}</h2></div><span className="badge pending">{t('Not covered','शामिल नहीं')}</span></div><p className="muted small">{t('RBI’s state study covers states and UTs with their own legislature. This territory is funded mainly through the Union budget.','RBI का अध्ययन विधानसभा वाले राज्यों और केंद्र शासित प्रदेशों को कवर करता है। यह क्षेत्र मुख्यतः केंद्रीय बजट से चलता है।')}</p>{city}</section>;
 const src=[...new Set(v.rows.map(r=>r.sourceId))].map(id=>sources.find(s=>s.id===id)!).filter(Boolean);
 return <section className="panel state-finance" id="state-story" aria-labelledby="state-finance-title"><div className="panel-heading"><div><span className="eyebrow small">{t('STATE FINANCES','राज्य वित्त')} · {year} · {periodKind(v.kind,hi)}</span><h2 id="state-finance-title">{t(`Where ${name}’s money comes from and goes`,`${name} का पैसा कहाँ से आता है और कहाँ जाता है`)}</h2></div><span className="badge derived">{t('Derived shares','व्युत्पन्न हिस्से')}</span></div>
  <div className="state-cols"><div><h3>{t('Every ₹100 of income came from…','आय के हर ₹100…')}</h3><ShareBars items={v.income} hi={hi} all={detailed} explain/></div><div><h3>{t('Every ₹100 of day-to-day spending went to…','रोज़मर्रा के ख़र्च के हर ₹100…')}</h3><ShareBars items={v.spend} hi={hi} all={detailed} explain/></div></div>
  <div className="info-banner"><Info size={18}/><p>{t('Day-to-day (revenue) account only. Building new roads and other capital spending is not included. Shares come from RBI figures expressed as % of the state’s economy (GSDP), rounded to 0.1, so each ₹ value can be off by about ₹1. Rupee amounts are not connected yet.','केवल रोज़मर्रा (राजस्व) खाता। नई सड़कें और अन्य पूंजीगत ख़र्च शामिल नहीं। हिस्से RBI के आंकड़ों (राज्य की अर्थव्यवस्था/GSDP के % में, 0.1 तक गोल) से निकाले गए हैं, इसलिए हर ₹ मान लगभग ₹1 ऊपर-नीचे हो सकता है। रुपये की राशि अभी नहीं जुड़ी है।')}</p></div>
  <p className="muted small state-source">{t('Source','स्रोत')}: {src.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={12}/></a>)}{detailed&&<> · SHA-256 {src.map(s=>s.sha256.slice(0,12)).join(', ')}… · {src[0]?.retrieval}</>}</p>
  {city}</section>;
}
function Municipal({dataset,hi,detailed,onSource}:{dataset:Dataset;hi:boolean;detailed:boolean;onSource:(r:MoneyRecord)=>void}){
 const t=(a:string,b:string)=>hi?b:a;const records=dataset.records.filter(r=>r.geographyId==='pmc');
 const sum=(rows:MoneyRecord[])=>rows.reduce((a,r)=>a+BigInt(r.amountRupees),0n);
 const columns=([['municipal-income','Came in','आया','Revenue income','राजस्व आय','IN-1 to IN-9'],['municipal-expenditure','Went out','गया','Revenue expenditure','राजस्व व्यय','EX-1 to EX-9']] as const).map(([group,flowEn,flowHi,en,hn,range])=>{const rows=records.filter(r=>r.group===group).sort((a,b)=>Number(BigInt(b.amountRupees)-BigInt(a.amountRupees)));return {group,flowEn,flowHi,en,hn,range,rows,total:sum(rows)};});
  return <section className="panel muni-panel" aria-labelledby="muni-title"><div className="panel-heading"><div><span className="eyebrow small">{t('PUNE MUNICIPAL CORPORATION · AUDITED ACCOUNTS','पुणे महानगरपालिका · लेखापरीक्षित खाते')} {records[0].fiscalYear}</span><h2 id="muni-title">{t('How the city’s money came in and went out','शहर का पैसा कैसे आया और कहाँ गया')}</h2></div><Official hi={hi}/></div>
 <MoneyStory income={columns[0].rows} expense={columns[1].rows} fiscalYear={records[0].fiscalYear} hi={hi} onSource={onSource}/>
 <details className="table-toggle" open={detailed}><summary>{t('View as table','तालिका के रूप में देखें')}<ChevronDown size={15}/></summary>
 <div className="info-banner"><Info size={18}/><p>{t('For experts: audited accrual accounts. Income counts when it falls due, not only when cash arrives. These are revenue-account totals. Capital works, depreciation and transfers to funds are not included, so “came in” minus “went out” is not money left over. This is not the city budget.','लेखापरीक्षित उपार्जन खाते: आय देय होने पर गिनी जाती है, केवल नकद मिलने पर नहीं। ये राजस्व खाते के योग हैं। पूंजीगत कार्य, मूल्यह्रास और निधियों में हस्तांतरण शामिल नहीं हैं, इसलिए “आया” घटा “गया” बची हुई राशि नहीं है। यह शहर का बजट नहीं है।')}</p></div>
 <div className="muni-columns">{columns.map(c=><div key={c.group}><div className="muni-total"><span>{t(c.en,c.hn)}</span><strong>{formatMoney(c.total.toString())}</strong><span className="badge derived">{t('Derived','व्युत्पन्न')}</span><small>{t(`Sum of ${c.rows.length} official schedule totals (${c.range})`,`${c.rows.length} आधिकारिक अनुसूची योगों का जोड़ (${c.range})`)}</small></div>
 <ul className="muni-list">{c.rows.map(r=>{const share=shareBasisPoints(BigInt(r.amountRupees),c.total);return <li key={r.id}><div className="muni-row"><span>{hi?r.labelHi:r.label}<small>{detailed?r.period.split('· ')[1]+` · PDF p.${r.sourcePage}`:share<10?'<0.1%':`${(share/100).toFixed(1)}%`}</small></span><Amount record={r} onClick={onSource}/></div><span className="coverage-track" aria-hidden="true"><i style={{width:`${share/100}%`}}/></span></li>;})}</ul></div>)}</div></details>
 <div className="built"><h3>{t('What was built with it?','इससे क्या बनाया गया?')}</h3><div className="built-grid">{[[Building2,'Projects','परियोजनाएं','Name, location, sanctioned amount, progress','नाम, स्थान, स्वीकृत राशि, प्रगति'],[FileText,'Tenders','निविदाएं','Estimated value, number of bids','अनुमानित मूल्य, बोलियों की संख्या'],[ReceiptText,'Contracts','अनुबंध','Awarded value, award date, period','आवंटित मूल्य, तारीख, अवधि'],[Users,'Contractors','ठेकेदार','Who received which contracts','किसे कौन से अनुबंध मिले']].map(([Icon,en,hn,den,dhn])=>{const I=Icon as LucideIcon;return <div className="built-card" key={en as string}><I size={20}/><strong>{t(en as string,hn as string)}</strong><small>{t(den as string,dhn as string)}</small><span className="badge pending">{t('Not connected','नहीं जुड़ा')}</span></div>;})}</div>
 <p className="muted small">{t('These appear here once an authoritative public source for Pune is connected, such as Maharashtra’s e-tendering portal or PMC project disclosures, where they can be collected without login or CAPTCHA. Contract value will always be shown separately from money actually paid.','पुणे के लिए आधिकारिक सार्वजनिक स्रोत (जैसे महाराष्ट्र ई-निविदा पोर्टल या PMC परियोजना प्रकटीकरण) बिना लॉगिन या CAPTCHA के जुड़ने पर ये यहाँ दिखेंगे। अनुबंध मूल्य हमेशा वास्तविक भुगतान से अलग दिखाया जाएगा।')}</p></div>
 </section>;
}
function Schemes({dataset,hi,onSource}:{dataset:Dataset;hi:boolean;onSource:(r:MoneyRecord)=>void}){
 const [search,setSearch]=useState('');const rows=dataset.records.filter(r=>r.group==='scheme'&&r.fiscalYear==='2026-27'&&r.valueType==='BE'&&`${r.label} ${r.labelHi}`.toLowerCase().includes(search.toLowerCase()));
 const ministry:Record<string,string>={samagra:'Ministry of Education','pm-shri':'Ministry of Education',pmjay:'Ministry of Health and Family Welfare','pmay-urban':'Ministry of Housing and Urban Affairs',amrut:'Ministry of Housing and Urban Affairs'};
 return <><label className="search-field"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={hi?'योजना खोजें…':'Find a scheme…'}/></label><div className="scheme-grid">{rows.map(r=><article className="panel scheme-card" key={r.id}><div className="stat-top"><span className="stat-icon mint"><HandCoins size={22}/></span><Official hi={hi}/></div><h2>{hi?r.labelHi:r.label}</h2><p>{ministry[r.metric]}</p><span className="eyebrow">2026–27 · {hi?'बजट अनुमान':'BUDGET ESTIMATE'}</span><Amount record={r} onClick={onSource}/><details><summary>{hi?'पिछले आंकड़े और उपलब्धता':'History & coverage'}<ChevronDown size={15}/></summary>{dataset.records.filter(x=>x.metric===r.metric&&x.id!==r.id).map(x=><div className="scheme-history" key={x.id}><small>{x.fiscalYear} · {valueLabels[x.valueType]}</small><Amount record={x} onClick={onSource}/></div>)}<p>{hi?'लाभार्थी, परिणाम और राज्य के अनुसार आंकड़े: अभी उपलब्ध नहीं।':'Beneficiaries, outcomes and state distribution: not connected.'}</p></details></article>)}</div>{!rows.length&&<Empty title={hi?'कोई मिलान नहीं':'No matching schemes'} text={hi?'अभी सीमित योजनाएं जुड़ी हैं।':'Only a selected set of major schemes is currently connected.'}/>}</>;
}
function Signals({hi}:{hi:boolean}){
 const [demo,setDemo]=useState(false);const t=(a:string,b:string)=>hi?b:a;
 return <><div className="info-banner"><Info size={20}/><p>{SIGNAL_DISCLAIMER}</p></div><div className="panel-heading signal-heading"><span className="badge official">{t('Live signals from official project reports and contract awards','आधिकारिक परियोजना रिपोर्ट और अनुबंधों से वास्तविक संकेत')}</span><button className="outline" onClick={()=>setDemo(!demo)} aria-pressed={demo}><SlidersHorizontal size={16}/>{demo?t('Hide rule examples','नियम उदाहरण छिपाएं'):t('Explore rule examples','नियम उदाहरण देखें')}</button></div>{!demo?<LiveSignals hi={hi}/>:<><div className="demo-banner">{t('SYNTHETIC EXAMPLES — these inputs do not describe any real project, government or contractor.','काल्पनिक उदाहरण — ये किसी वास्तविक परियोजना, सरकार या ठेकेदार के आंकड़े नहीं हैं।')}</div><div className="signals-grid">{demonstrationSignals().map(s=><article className="panel signal-card" key={s.rule}><div className="stat-top"><span className="stat-icon peach"><Activity size={21}/></span><span className="neutral-tag">{t('Rule example','नियम उदाहरण')}</span></div><h3>{s.rule.replaceAll('-',' ')}</h3><p>{s.explanation}</p><details><summary>{t('Inspect inputs & method','आंकड़े और पद्धति देखें')}<ChevronDown size={15}/></summary><dl>{Object.entries(s.inputs).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}<div><dt>Formula</dt><dd>{s.formula}</dd></div><div><dt>Comparison period</dt><dd>{s.comparisonPeriod}</dd></div><div><dt>Source</dt><dd>{s.source}</dd></div><div><dt>Generated</dt><dd>{s.generatedAt}</dd></div></dl><p>{s.limitations}</p></details><small>{s.disclaimer}</small></article>)}</div></>}</>;
}
function Ask({hi,dataset,onSource}:{hi:boolean;dataset:Dataset;onSource:(r:MoneyRecord)=>void}){
 const [q,setQ]=useState(''),[busy,setBusy]=useState(false),[answer,setAnswer]=useState<{answer:string;records:MoneyRecord[]}|null>(null);
 const ask=async(question:string)=>{if(!question.trim()||busy)return;setQ(question);setBusy(true);try{if(question.length>500)throw new Error('Question too long');setAnswer(executeQuery(await localProvider.interpret(question),dataset) as {answer:string;records:MoneyRecord[]});}catch{setAnswer({answer:hi?'सेवा उपलब्ध नहीं है। फिर प्रयास करें।':'The query service is unavailable. Please try again.',records:[]});}finally{setBusy(false);}};
 return <div className="ask-panel panel"><span className="ask-icon"><Sparkles size={29}/></span><h2>{hi?'हर सवाल की शुरुआत जिज्ञासा से होती है।':'A little curiosity goes a long way.'}</h2><p>{hi?'जुड़े बजट आंकड़ों के बारे में पूछें।':'Ask about the budget records currently connected to Paisa.'}</p><form className="ask-form" onSubmit={e=>{e.preventDefault();void ask(q);}}><input aria-label="Ask Paisa a question" maxLength={500} value={q} onChange={e=>setQ(e.target.value)} placeholder={hi?'शिक्षा के लिए कितना बजट है?':'How much is budgeted for education?'}/><button className="primary" disabled={busy||!q.trim()} type="submit">{busy?'…':<ArrowRight size={20}/>}<span className="sr-only">Ask</span></button></form><div className="suggestions">{(hi?['शिक्षा के लिए बजट','खाद्य सब्सिडी का बजट','पुणे की परियोजनाएं']:['How much is budgeted for education?','What is the food subsidy budget?','How much GST was collected this year?','Show Pune projects']).map(s=><button key={s} onClick={()=>void ask(s)}>{s}<ArrowUpRight size={14}/></button>)}</div><div aria-live="polite">{answer&&<div className="answer"><span className="eyebrow">PAISA</span><p>{answer.answer}</p>{answer.records.map(r=><button className="source-link" key={r.id} onClick={()=>onSource(r)}><FileText size={16}/>{r.sourceId==='cga'?'CGA Monthly Accounts':'Union Budget 2026–27'} · {r.sourcePage}<ExternalLink size={13}/></button>)}{answer.answer===NO_DATA&&<Link className="text-link" href="/sources">{hi?'डेटा की उपलब्धता देखें':'See what is connected'}<ArrowRight size={15}/></Link>}</div>}</div><p className="ask-footnote"><ShieldCheck size={14}/>{hi?'बीटा: सीमित प्रश्न-प्रकार। जवाब प्रकाशित रिकॉर्ड से आते हैं।':'Beta: constrained question matching. Answers come from published records; no LLM is connected.'}</p></div>;
}
const statusLabel:Record<'behind'|'failing',[string,string]>={behind:['Waiting for newer data','नए डेटा की प्रतीक्षा'],failing:['Last check failed','पिछली जांच विफल']};
const modeLabel:Record<Exclude<ConnectorStatus['mode'],'not-connected'>,[string,string]>={daily:['checked daily','रोज़ जांच'],monthly:['checked monthly','मासिक जांच'],'manual-annual':['added by hand yearly','हर साल हाथ से जोड़ा जाता है']};
function Sources({dataset,hi}:{dataset:Dataset;hi:boolean}){
 const [status,setStatus]=useState<ConnectorStatus[]>([]);
 useEffect(()=>{staticApi<{connectors:ConnectorStatus[]}>('/api/v1/status').then(x=>setStatus(x.connectors)).catch(()=>{});},[]);
 return <><div className="info-banner"><ShieldCheck size={21}/><p>{hi?'आंकड़े आधिकारिक स्रोतों से पढ़े गए हैं, सहेजी गई प्रतियों से मिलाए गए हैं और उनके योग जांचे गए हैं। प्रकाशित डेटा फ़ाइलें /data/ पर सार्वजनिक हैं; कई सरकारी स्रोतों की पुन: उपयोग शर्तों की समीक्षा अभी बाकी है।':'Figures are read from official sources, checked against saved copies and reconciled with their totals. The published data files are public at /data/; reuse terms for several government sources are still under review.'}</p></div><div className="source-list">{dataset.sources.map(s=><article className="panel source-card" key={s.id}><div className="source-title"><span className="stat-icon mint"><FileText size={22}/></span><div><h2>{s.title??(s.id==='cga'?'CGA · Monthly accounts':`Union Budget · ${({bag1:'Budget at a Glance',bag5:'Receipts',bag6:'Expenditure',bag7:'Major schemes'} as Record<string,string>)[s.id]}`)}</h2><p>{s.authority??(s.id==='cga'?'Controller General of Accounts':'Ministry of Finance, Government of India')}</p></div><Official hi={hi}/></div><dl className="source-meta"><div><dt>{hi?'संस्करण':'Dataset version'}</dt><dd>{s.datasetVersion}</dd></div><div><dt>{hi?'प्राप्त किया':'Retrieved'}</dt><dd>{new Date(s.retrievedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</dd></div><div><dt>Parser</dt><dd>{s.parserVersion}</dd></div><div><dt>{hi?'लाइसेंस':'Licence'}</dt><dd>{s.license.name}</dd></div></dl><details><summary>SHA-256 & attribution<ChevronDown size={15}/></summary><code>{s.sha256}</code><p>{s.license.attribution}</p><a href={s.license.url} target="_blank" rel="noreferrer">Source terms reference <ExternalLink size={13}/></a></details><a className="source-link" href={s.url} target="_blank" rel="noreferrer">{hi?'मूल आधिकारिक स्रोत खोलें':'Open original government source'}<ExternalLink size={15}/></a></article>)}</div><div className="panel label-key"><h2>{hi?'लेबल कैसे पढ़ें':'How to read the labels'}</h2><ul>
  <li><span className="link-tag published">{hi?'प्रकाशित':'Published'}</span>{hi?'आधिकारिक दस्तावेज़ में छपा आंकड़ा, जैसा है।':'A figure printed in an official document, as it is.'}</li>
  <li><span className="link-tag verified">{hi?'सत्यापित कड़ी':'Verified link'}</span>{hi?'रिकॉर्ड ख़ुद दो चीज़ों को जोड़ते हैं, जैसे एक अनुबंध और उसे जीतने वाला प्रकाशित नाम।':'The records themselves connect two things, such as a contract and the published name that won it.'}</li>
  <li><span className="link-tag calc">{hi?'गणना':'Calculated'}</span>{hi?'प्रकाशित आंकड़ों से निकाला गया हिस्सा या तुलना, जैसे “हर ₹100 में से”।':'A share or comparison worked out from published figures, such as “out of every ₹100”.'}</li>
  <li><span className="link-tag missing">{hi?'कड़ी नहीं':'Missing link'}</span>{hi?'जोड़ने के लिए ज़रूरी रिकॉर्ड सार्वजनिक नहीं हैं या अभी जुड़े नहीं हैं। पैसा अंदाज़ा नहीं लगाता।':'The records needed to connect them are not public or not connected yet. Paisa does not guess.'}</li></ul></div>
 <div className="panel"><div className="panel-heading"><h2>{hi?'डेटा कितना ताज़ा है':'How fresh is the data'}</h2>{REPO_URL&&<a className="neutral-tag" href={`${REPO_URL}/actions/workflows/update-data.yml`} target="_blank" rel="noreferrer">{hi?'आज की स्वचालित जांच':'Today’s automatic check'}<ExternalLink size={11}/></a>}</div>
  <div className="status-row status-head" aria-hidden="true"><small>{hi?'स्रोत':'Source'}</small><small>{hi?'अवधि':'Data covers'}</small><small>{hi?'अंतिम सत्यापन · अपडेट':'Last verified · updates'}</small></div>
  {status.map(s=><div className="status-row" key={s.id}><span><strong>{hi?s.nameHi:s.name}</strong>{s.state!=='ok'&&s.state!=='not-connected'&&<span className="badge pending">{statusLabel[s.state][hi?1:0]}</span>}{s.note&&<small className="status-note">{s.note}</small>}</span>
   <span>{s.period??(hi?'अभी नहीं जुड़ा':'Not connected yet')}</span><small>{s.lastVerified?new Date(s.lastVerified).toLocaleDateString(hi?'hi-IN':'en-IN',{day:'numeric',month:'short',year:'numeric'}):'—'}{s.mode!=='not-connected'&&` · ${modeLabel[s.mode][hi?1:0]}`}</small></div>)}
  <p className="muted small">{hi?'“अंतिम सत्यापन” वह तारीख है जब साइट पर दिखा डेटा डाउनलोड हुआ और हर जांच में सही पाया गया। अवधि बताती है कि डेटा किस समय का है। रोज़ की जांच का परिणाम GitHub पर सार्वजनिक है।':'“Last verified” is when the data on this site was downloaded and passed every check. “Data covers” is the period the figures describe. The result of every daily check, including days with nothing new, is public on GitHub.'}</p></div><div className="panel"><h2>{hi?'मिलान जांच':'Reconciliation checks'}</h2><div className="validation-list">{dataset.validations.map(v=><div key={v.rule}><CheckCircle2 size={16}/><span>{v.rule}</span><small>{hi?'सफल':'Passed'}</small></div>)}</div><p className="muted small">{hi?'प्रकाशन':'Published'}: {new Date(dataset.publishedAt).toLocaleString('en-IN')}. Tolerances and raw differences are available in the provenance API.</p></div></>;
}
function About({hi}:{hi:boolean}){return <div className="about-grid"><article className="panel"><span className="stat-icon mint"><Globe2 size={25}/></span><h2>{hi?'सार्वजनिक धन। सार्वजनिक ज्ञान।':'Public money. Public knowledge.'}</h2><p>{hi?'पैसा एक स्वतंत्र, निष्पक्ष और ओपन-सोर्स परियोजना है। इसका उद्देश्य सरकारी धन को नागरिकों के लिए समझने योग्य बनाना है।':'PAISA is an independent, politically neutral, open-source project that makes public finances understandable and verifiable for every citizen.'}</p><h3>{hi?'हमारा वादा':'Our promise'}</h3><ul><li>Budget allocations, revised estimates, expenditure, releases, awards, payments, progress and outcomes stay distinct.</li><li>No political rankings or accusations. Signals are mathematical observations with limitations.</li><li>Missing evidence means a visible gap. It never becomes an invented link.</li><li>No sign-in, PAN, Aadhaar or bank details. My Tax runs locally without retaining the amount.</li></ul></article><article className="panel"><h2>{hi?'क्या उपलब्ध है':'What is connected'}</h2><p>Union Budget 2026–27, comparative estimates and annual actuals, selected major schemes, and CGA provisional April–August 2026 aggregates.</p><h3>{hi?'क्या बाकी है':'What remains'}</h3><p>Pune municipal finance, project-to-contract relationships, contractor records, verified geographic codes, and five additional live connectors. The geographic model supports urban and rural hierarchies.</p><p>Signal rules are implemented and tested on isolated synthetic fixtures. No live project or procurement signals are published.</p><h3>{hi?'ओपन सोर्स':'Open source'}</h3><p>Project-authored code: AGPL-3.0-only. Government datasets retain separate source terms. No government endorsement is implied. Hindi is an initial translation; specialist terminology needs human review.</p><Link href="/sources" className="text-link">Inspect sources & checks <ArrowRight size={16}/></Link></article></div>;}
function Provenance({record:r,source:s,detailed,hi,close,records}:{record:MoneyRecord;source:Source;detailed:boolean;hi:boolean;close:()=>void;records:MoneyRecord[]}){
 const ref=useRef<HTMLDialogElement>(null);const t=(a:string,b:string)=>hi?b:a;
 useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);
 // Only figures of the same kind and from the same series are compared (budget estimates with budget estimates, never part-year accounts with full-year ones).
 const family=(x:MoneyRecord)=>x.sourceId==='cga'?'cga':x.sourceId.startsWith('bag')?'budget':x.sourceId;
 const same=records.filter(x=>x.metric===r.metric&&x.group===r.group&&x.geographyId===r.geographyId);
 const series=same.filter(x=>family(x)===family(r)&&x.valueType===r.valueType).sort((a,b)=>a.fiscalYear.localeCompare(b.fiscalYear));
 const others=same.filter(x=>x.id!==r.id&&!series.includes(x)).sort((a,b)=>a.fiscalYear.localeCompare(b.fiscalYear)||a.valueType.localeCompare(b.valueType));
 const max=series.reduce((m,x)=>BigInt(x.amountRupees)>m?BigInt(x.amountRupees):m,1n);
 const city=r.sourceId==='cityfinance-ulb-accounts';const level:ConcernSubject['level']=r.sourceId.startsWith('pmc-')||city?'city':'central';
 const authority=city?(r.period.split(' · ')[1]??s.authority??''):r.sourceId.startsWith('pmc-')?'Pune Municipal Corporation':r.sourceId==='cga'?'Controller General of Accounts, Ministry of Finance':'Department of Economic Affairs, Ministry of Finance';
 const m=NATIONAL[r.metric];const local=plain[r.metric];const what=hi?(m?.whatHi??local?.whatHi):(m?.what??local?.what);
 const who=hi?m?.whoHi:m?.who;const kind=VALUE_TYPE[r.valueType]??[r.valueType,r.valueType];
 const docTitle=s.title??(r.sourceId==='cga'?'Monthly Accounts of the Union Government (CGA)':`Union Budget ${s.datasetVersion??''} · Budget at a Glance`.replace('  ',' '));
 return <dialog ref={ref} className="provenance-dialog" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close();}} aria-labelledby="provenance-title"><div className="provenance-content">
  <div className="panel-heading"><span className="eyebrow">{t('BEHIND THE NUMBER','आंकड़े के पीछे')}</span><button className="icon-button" autoFocus onClick={close} aria-label={t('Close','बंद करें')}><X size={21}/></button></div>
  <h2 id="provenance-title">{hi?r.labelHi:r.label}</h2>
  <div className="provenance-amount">{formatMoney(r.amountRupees)}<span className="link-tag published">{t('Published','प्रकाशित')}</span></div>
  <p className="provenance-period">{r.fiscalYear} · {kind[hi?1:0]}</p>
  {what&&<section className="drawer-block"><h3>{t('What this means','इसका अर्थ')}</h3><p>{what}</p></section>}
  {series.length>1&&<section className="drawer-block"><h3>{t('How it has changed','कैसे बदला')}</h3>
   <div className="drawer-trend" role="img" aria-label={series.map(x=>`${x.fiscalYear}: ${formatMoney(x.amountRupees)}`).join(', ')}>{series.map(x=><span key={x.id} className={x.id===r.id?'on':''}><em>{formatMoney(x.amountRupees)}</em><i style={{height:`${Number(BigInt(x.amountRupees)*100n/max)}%`}}/><small>{x.fiscalYear}</small></span>)}</div>
   <p className="muted small">{t(`Comparing ${kind[0].split(':')[0].toLowerCase()}s only, from the same series.`,`केवल एक ही प्रकार (${kind[1].split(':')[0]}) के आंकड़ों की तुलना।`)}</p></section>}
  {others.length>0&&<section className="drawer-block"><h3>{t('Other published figures for this item','इस मद के अन्य प्रकाशित आंकड़े')}</h3><ul className="drawer-others">{others.map(x=><li key={x.id}><span>{x.fiscalYear} · {(VALUE_TYPE[x.valueType]??[x.valueType,x.valueType])[hi?1:0].split(':')[0]}{x.sourceId==='cga'?` · ${t('part year','आंशिक वर्ष')}`:''}</span><strong>{formatMoney(x.amountRupees)}</strong></li>)}</ul></section>}
  <section className="drawer-block"><h3>{t('Where it goes','कहाँ जाता है')}</h3><p>{who??t('Official records published so far do not name who received this money.','अब तक प्रकाशित आधिकारिक रिकॉर्ड में पाने वालों के नाम नहीं हैं।')} <span className="link-tag missing">{t('Recipients not published','पाने वाले प्रकाशित नहीं')}</span></p></section>
  <section className="drawer-block"><h3>{t('Source','स्रोत')}</h3><p>{docTitle}{r.sourceId==='cga'?'':` · ${t('page','पृष्ठ')} ${r.sourcePage}`}<br/><span className="muted small">{s.authority??authority}</span></p>
   {r.notes&&<div className="info-banner"><Info size={16}/>{r.notes}</div>}
   <a className="primary" href={s.url+(r.sourceId==='cga'||city?'':`#page=${r.sourcePage}`)} target="_blank" rel="noreferrer">{t('Open official source','आधिकारिक स्रोत खोलें')}<ExternalLink size={16}/></a></section>
  <details className="drawer-technical" open={detailed}><summary>{t('Technical details','तकनीकी विवरण')}<ChevronDown size={16}/></summary><dl className="raw-details"><div><dt>{t('Period','अवधि')}</dt><dd>{r.period}</dd></div><div><dt>Raw value</dt><dd>{r.rawValue} {r.rawUnit}</dd></div><div><dt>Parsed integer rupees</dt><dd>{r.amountRupees}</dd></div><div><dt>Transformation</dt><dd>{r.rawUnit==='rupee'?'Source rupees (Indian digit grouping), commas removed':'Source crore × 10,000,000 = rupees'}</dd></div><div><dt>Parser</dt><dd>{r.parserVersion}</dd></div><div><dt>Retrieved</dt><dd>{r.retrievedAt}</dd></div><div><dt>SHA-256</dt><dd><code>{r.snapshotHash}</code></dd></div><div><dt>Licence</dt><dd>{s.license.name}</dd></div><div><dt>Attribution</dt><dd>{s.license.attribution}</dd></div></dl></details>
  <Concern hi={hi} subject={{what:hi?r.labelHi:r.label,amount:formatMoney(r.amountRupees),period:`${r.fiscalYear} (${kind[0].split(':')[0]})`,authority,level,source:{title:docTitle,url:s.url,page:r.sourceId==='cga'||city?undefined:r.sourcePage}}}/>
  <p className="muted small">{t('Paisa is independent. An official source does not imply government endorsement.','पैसा स्वतंत्र है। आधिकारिक स्रोत का अर्थ सरकारी समर्थन नहीं।')}</p></div></dialog>;
}
