BEGIN;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE TYPE dataset_state AS ENUM ('RAW','PARSED','VALIDATED','PUBLISHED','REJECTED');
CREATE TYPE money_type AS ENUM ('BE','RE','ACTUAL','RELEASE','TENDER_VALUE','AWARDED_VALUE','PAYMENT','SANCTIONED');
CREATE TYPE geography_type AS ENUM ('country','state','ut','district','urban','rural','ulb','ward','block','gram_panchayat','village','project');
CREATE TABLE fiscal_years(id text PRIMARY KEY, starts_on date NOT NULL, ends_on date NOT NULL, CHECK(ends_on>starts_on));
CREATE TABLE sources(id text PRIMARY KEY, authority text NOT NULL, dataset text NOT NULL, url text NOT NULL CHECK(url LIKE 'https://%'), licence jsonb NOT NULL, attribution text NOT NULL, licence_reviewed_at timestamptz, redistribution_allowed boolean NOT NULL DEFAULT false);
CREATE TABLE source_snapshots(id text PRIMARY KEY CHECK(id ~ '^[a-f0-9]{64}$'),source_id text NOT NULL REFERENCES sources,source_url text NOT NULL,retrieved_at timestamptz NOT NULL,http_metadata jsonb NOT NULL,object_key text NOT NULL UNIQUE,parser_version text NOT NULL,dataset_version text NOT NULL,licence_at_retrieval jsonb NOT NULL);
CREATE FUNCTION reject_snapshot_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Source snapshots are immutable'; END $$;
CREATE TRIGGER immutable_snapshots BEFORE UPDATE OR DELETE ON source_snapshots FOR EACH ROW EXECUTE FUNCTION reject_snapshot_mutation();
CREATE TABLE datasets(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,source_id text REFERENCES sources,state dataset_state NOT NULL DEFAULT 'RAW',created_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz);
CREATE TABLE geographies(id text PRIMARY KEY,parent_id text REFERENCES geographies,name text NOT NULL,type geography_type NOT NULL,official_code text,code_system text,boundary geometry(MultiPolygon,4326),CHECK((official_code IS NULL)=(code_system IS NULL)));
CREATE UNIQUE INDEX geographic_official_ids ON geographies(code_system,official_code) WHERE official_code IS NOT NULL;
CREATE INDEX geographic_boundary ON geographies USING gist(boundary);
CREATE TABLE government_entities(id text PRIMARY KEY,name text NOT NULL,geography_id text REFERENCES geographies,level text NOT NULL CHECK(level IN('central','state','municipal','rural')));
CREATE TABLE ministries(id text PRIMARY KEY,name text NOT NULL,government_id text REFERENCES government_entities);
CREATE TABLE departments(id text PRIMARY KEY,name text NOT NULL,ministry_id text REFERENCES ministries);
CREATE TABLE schemes(id text PRIMARY KEY,name text NOT NULL,department_id text REFERENCES departments);
CREATE TABLE subsidies(id text PRIMARY KEY,scheme_id text REFERENCES schemes,category text NOT NULL);
CREATE TABLE benefits(id text PRIMARY KEY,scheme_id text REFERENCES schemes,official_eligibility_text text,source_snapshot text REFERENCES source_snapshots);
CREATE TABLE projects(id text PRIMARY KEY,name text NOT NULL,geography_id text REFERENCES geographies,agency_id text REFERENCES government_entities,sector text NOT NULL,location geometry(Point,4326),expected_completion date);
CREATE INDEX project_locations ON projects USING gist(location);
CREATE TABLE contractors(id text PRIMARY KEY,legal_name text NOT NULL,official_identifier text,identifier_system text,aliases jsonb NOT NULL DEFAULT '[]',resolution_evidence text REFERENCES source_snapshots);
CREATE UNIQUE INDEX contractor_official_id ON contractors(identifier_system,official_identifier) WHERE official_identifier IS NOT NULL;
CREATE INDEX contractor_names ON contractors USING gin(legal_name gin_trgm_ops);
CREATE TABLE tenders(id text PRIMARY KEY,official_id text NOT NULL,authority_id text REFERENCES government_entities,title text NOT NULL,bid_count integer CHECK(bid_count>=0),qualified_bid_count integer CHECK(qualified_bid_count>=0),source_snapshot text REFERENCES source_snapshots);
CREATE TABLE bidders(id text PRIMARY KEY,tender_id text NOT NULL REFERENCES tenders,contractor_id text REFERENCES contractors,published_name text NOT NULL,qualified boolean);
CREATE TABLE contracts(id text PRIMARY KEY,tender_id text REFERENCES tenders,contractor_id text REFERENCES contractors,award_date date,period_start date,period_end date,source_snapshot text REFERENCES source_snapshots);
CREATE TABLE provenance_records(id text PRIMARY KEY,snapshot_id text NOT NULL REFERENCES source_snapshots,raw_value text NOT NULL,raw_unit text NOT NULL,parsed_rupees numeric(30,0) NOT NULL CHECK(parsed_rupees>=0),parser_version text NOT NULL,source_locator text NOT NULL,derivation jsonb,classification text NOT NULL CHECK(classification IN('official','derived','calculated')));
CREATE TABLE money_records(id text PRIMARY KEY,dataset_id bigint NOT NULL REFERENCES datasets,entity_type text NOT NULL,entity_id text NOT NULL,metric text NOT NULL,fiscal_year text NOT NULL REFERENCES fiscal_years,value_type money_type NOT NULL,amount_rupees numeric(30,0) NOT NULL CHECK(amount_rupees>=0),period_start date NOT NULL,period_end date NOT NULL,provenance_id text NOT NULL REFERENCES provenance_records,CHECK(period_end>=period_start));
CREATE VIEW published_money_records AS SELECT m.* FROM money_records m JOIN datasets d ON d.id=m.dataset_id WHERE d.state='PUBLISHED';
CREATE TABLE revenue_sources(id text PRIMARY KEY,name text NOT NULL,parent_id text REFERENCES revenue_sources);
CREATE VIEW revenue_records AS SELECT * FROM published_money_records WHERE entity_type='revenue';
CREATE VIEW budgets AS SELECT * FROM published_money_records WHERE value_type IN('BE','RE');
CREATE VIEW budget_items AS SELECT * FROM budgets;
CREATE VIEW expenditures AS SELECT * FROM published_money_records WHERE value_type='ACTUAL';
CREATE VIEW fund_releases AS SELECT * FROM published_money_records WHERE value_type='RELEASE';
CREATE TABLE progress_updates(id text PRIMARY KEY,project_id text NOT NULL REFERENCES projects,reported_at date NOT NULL,physical_pct numeric(5,2) CHECK(physical_pct BETWEEN 0 AND 100),financial_pct numeric(5,2) CHECK(financial_pct BETWEEN 0 AND 100),financial_basis text NOT NULL,snapshot_id text NOT NULL REFERENCES source_snapshots);
CREATE TABLE outcomes(id text PRIMARY KEY,entity_type text NOT NULL,entity_id text NOT NULL,indicator text NOT NULL,value numeric,unit text NOT NULL,period text NOT NULL,snapshot_id text NOT NULL REFERENCES source_snapshots);
CREATE TABLE evidenced_relationships(id text PRIMARY KEY,from_type text NOT NULL,from_id text NOT NULL,to_type text NOT NULL,to_id text NOT NULL,relationship_type text NOT NULL,evidence_type text NOT NULL CHECK(evidence_type IN('direct_official','derived','illustrative')),snapshot_id text REFERENCES source_snapshots,effective_date date NOT NULL,explanation text NOT NULL,CHECK(evidence_type='illustrative' OR snapshot_id IS NOT NULL));
CREATE TABLE signal_rules(id text PRIMARY KEY,version text NOT NULL,thresholds jsonb NOT NULL,formula text NOT NULL);
CREATE TABLE signals(id text PRIMARY KEY,rule_id text NOT NULL REFERENCES signal_rules,inputs jsonb NOT NULL,formula text NOT NULL,comparison_period text NOT NULL,source_ids jsonb NOT NULL,generated_at timestamptz NOT NULL,explanation text NOT NULL,limitations text NOT NULL,disclaimer text NOT NULL,fixture boolean NOT NULL DEFAULT false);
CREATE VIEW public_signals AS SELECT * FROM signals WHERE fixture=false;
CREATE TABLE connector_runs(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,connector_id text NOT NULL,started_at timestamptz NOT NULL,finished_at timestamptz,status text NOT NULL,error text,last_verified_dataset bigint REFERENCES datasets);
CREATE TABLE validation_results(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,dataset_id bigint NOT NULL REFERENCES datasets,rule text NOT NULL,passed boolean NOT NULL,actual_rupees numeric(30,0),expected_rupees numeric(30,0),tolerance_rupees numeric(30,0),details jsonb);
CREATE FUNCTION protect_publication() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.state='PUBLISHED' AND (NOT EXISTS(SELECT 1 FROM validation_results WHERE dataset_id=NEW.id) OR EXISTS(SELECT 1 FROM validation_results WHERE dataset_id=NEW.id AND NOT passed)) THEN RAISE EXCEPTION 'Publication requires successful validation'; END IF;
 RETURN NEW; END $$;
CREATE TRIGGER publication_gate BEFORE UPDATE OF state ON datasets FOR EACH ROW EXECUTE FUNCTION protect_publication();
COMMIT;
